In [81]:
import numpy as np
import pandas as pd

In [82]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [83]:
df=pd.read_csv('gurgaon_properties.csv')

In [84]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2971,2 BHK Flat in Sector 88B Gurgaon,flat,vatika xpressions,1.10,8148.0,1350.0,Built Up area: 1350 (125.42 sq.m.)Carpet area:...,2,4,3+,study room,"H 23, Sector 88B Gurgaon, Gurgaon, Haryana",2.0,North-East,Under Construction,"['Dwarka Expressway', 'Adarsh public school,Ga...",We are the proud owners of this 2 bhk apartmen...,NaN,"['Feng Shui / Vaastu Compliant', 'Intercom Fac...",NaN
259,4 Bedroom House for sale in Sector 91 Gurgaon,house,dlf new town heights,2.50,7058.0,3542.0,Plot area 3400(315.87 sq.m.),4,4,3+,"pooja room,study room,servant room,store room","Sector 91 Gurgaon, Gurgaon, Haryana",3.0,East,5 to 10 Year Old,"['MG Road Metro Station', 'RHM Public School',...","Dlf new town heights, 4bhk independent villa a...","['2 Bed', '7 Wardrobe', '9 Fan', '1 Exhaust Fa...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
52,3 BHK Flat in Sector 22 Gurgaon,flat,ambience creacions,4.30,13915.0,3090.0,Super Built up area 3090(287.07 sq.m.)Built Up...,3,4,3+,"servant room,others","A102, Sector 22 Gurgaon, Gurgaon, Haryana",6.0,South-West,1 to 5 Year Old,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...",This 3 bhk apartment is available for sale in ...,"['1 Water Purifier', '1 Fridge', '6 Fan', '1 E...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1443,2 BHK Flat in Sector 103 Gurgaon,flat,indiabulls centrum park,1.15,8679.0,1325.0,Super Built up area 1325(123.1 sq.m.)Carpet ar...,2,2,3,study room,"Higher, Sector 103 Gurgaon, Gurgaon, Haryana",10.0,North-East,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'HUDA Market, Sector 1...",Indiabulls centrum park is one of gurgaon's mo...,"['2 Wardrobe', '1 Water Purifier', '3 Fan', '2...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
3441,2 BHK Flat in Sector 79 Gurgaon,flat,godrej aria,1.30,9622.0,1351.0,Super Built up area 1351(125.51 sq.m.),2,4,2,not available,"Sector 79 Gurgaon, Gurgaon, Haryana",3.0,East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Delhi Jaipur Expressway'...",Enjoy uninterrupted views of aravalli hills\n1...,[],"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area4 out of 5', 'Construction5 out of..."

In [85]:
df.shape

(3960, 20)

In [86]:
df.duplicated().sum()

np.int64(0)

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3960 entries, 0 to 3959
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3960 non-null   object
 1   property_type    3960 non-null   object
 2   society          3959 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3960 non-null   object
 7   bedRoom          3960 non-null   int64
 8   bathroom         3960 non-null   int64
 9   balcony          3960 non-null   object
 10  additionalRoom   3960 non-null   object
 11  address          3949 non-null   object
 12  floorNum         3939 non-null   float64
 13  facing           2783 non-null   object
 14  agePossession    3959 non-null   object
 15  nearbyLocations  3753 non-null   object
 16  description      3960 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3251 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 618.9+ KB

In [88]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                19
price_per_sqft       19
area                 19
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1031
features            709
rating              449
dtype: int64

In [89]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 Bedroom House for sale in Sector 4 Gurgaon,house,independent,3.25,14444.0,2250.0,Plot area 250(209.03 sq.m.),3,3,2,not available,"Sector 4 Gurgaon, Gurgaon, Haryana",2.0,South-East,10+ Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Prat...",250 square yards east facing single story made...,"['30 Light', 'No AC', 'No Bed', 'No Chimney', ...","['Feng Shui / Vaastu Compliant', 'Park', 'Visi...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1,4 BHK Flat in Sector 67 Gurgaon,flat,bestech park view spa next,2.70,11489.0,2350.0,Super Built up area 2350(218.32 sq.m.),4,4,3+,"pooja room,servant room","Middle Floor, Sector 67 Gurgaon, Gurgaon, Haryana",9.0,South-West,5 to 10 Year Old,"['Omaxe City Centre Mall', 'Golf Course Extens...",Located in the popular residential address of ...,"['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Security / Fire...","['Green Area5 out of 5', 'Construction4 out of..."
2,4 Bedroom House for sale in Sector 109 Gurgaon,house,international city by sobha phase 1,6.75,10838.0,6228.0,Plot area 692(578.6 sq.m.),4,4,3+,"servant room,pooja room","Sector 109 Gurgaon, Gurgaon, Haryana",2.0,North-East,0 to 1 Year Old,"['Dwarka sector 21 metro station', 'Pacific D2...",International city is an urban enclave of vill...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Safety4.5 out of 5'..."
3,2 BHK Flat in Sohna,flat,hcbs sports ville,0.38,5067.0,750.0,Built Up area: 750 (69.68 sq.m.)Carpet area: 6...,2,2,2,not available,"Sohna, Sohna, Gurgaon, Haryana",9.0,East,undefined,"['The roadside cafe', 'GD Goenka Mess', 'ROyal...",Best in class property available at sohna loca...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area4 out of 5', 'Amenities4 out of 5'..."
4,2 BHK Flat in Sector 74 Gurgaon,flat,m3m skywalk,1.78,12500.0,1424.0,Carpet area: 1424 (132.29 sq.m.),2,2,3+,not available,"Sector 74, Delhi Gurgaon Expressway, Sector 74...",12.0,NaN,undefined,"['Omaxe Gurgaon Mall', 'Omaxe Celebration Mall...",Best in class property available at sector 74 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN

In [90]:
df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').value_counts()

property_name
Sohna                                                        163
Sector 102                                                   113
Sector 85                                                    110
Sector 92                                                    104
Sector 69                                                     94
Sector 65                                                     90
Sector 90                                                     90
Sector 81                                                     90
Sector 109                                                    88
Sector 79                                                     80
Sector 83                                                     69
Sector 37D                                                    68
Sector 86                                                     67
Sector 104                                                    66
Sector 107                                                    60
Sector 108                                                    59
Sector 95                                                     57
Sector 56                                                     57
Sector 48                                                     56
Sector 89                                                     56
Sector 70A                                                    54
Sector 70                                                     53
Sector 37C                                                    53
Nirvana Country                                               53
Sector-33 Sohna                                               51
Sector 84                                                     51
Palam Vihar                                                   50
Sector 67                                                     48
Sector 66                                                     46
Sector 103                                                    45
DLF Phase 1                                                   43
DLF Phase 2                                                   43
Sector 113                                                    43
Sector 61                                                     42
Sector 82                                                     42
Sector 106                                                    38
Sector 49                                                     36
Sector 99A                                                    32
Sushant Lok Phase 1                                           31
Sector 68                                                     30
Sector 72                                                     29
Sector 77                                                     29
Sector 54                                                     27
Laxman Vihar                                                  27
Sector 71                                                     27
DLF Phase 4                                                   26
Sector 112                                                    24
Sector 33                                                     23
Sector 88A                                                    23
Sector 111                                                    22
Sector 67A                                                    22
DLF Phase 3                                                   22
Sector 82A                                                    20
Sector 22                                                     20
Sector 78                                                     19
Sector 63A                                                    18
Sector 74                                                     18
Sector 62                                                     17
Sector 91                                                     17
Sector 110                                                    16
Sushant Lok Phase 3                                           16
Sector 99                                                     16
Sector 14                                                     15
Sector 60                                                     15
Sector 63                                                     15
Sector 1 Imt Manesar                                          14
DLF Phase 5                                                   14
Sector 3                                                      14
Sector 76                                                     14
Rajendra Park                                                 14
Gwal Pahari                                                   14
Sector 52                                                     14
Sector 53                                                     14
Sector 46                                                     13
Laxman Vihar Phase 2                                          13
Sector 36A                                                    13
Sector 39                                                     12
Sector 38                                                     12
Sector 31                                                     12
Uppals Southend                                               12
Sohna Road                                                    12
Sector 50                                                     12
Sector 93                                                     11
Sector 9A                                                     11
Sector 47                                                     11
Ashok Vihar Phase 3 Extension                                 11
Sector 1A IMT Manesar                                         10
Sector 7                                                      10
South City 1                                                   9
Sector 95A                                                     9
Sector 55                                                      9
Ashok Vihar Phase 2                                            9
Sector 4                                                       9
Malibu Town                                                    8
Sector 43                                                      8
Mehrauli  Road                                                 8
Sector 89 A                                                    8
Sector 57                                                      8
Sector 59                                                      8
Sector 10A                                                     8
C Block Sushant Lok Phase 1                                    8
Palam Vihar Extension                                          8
Dwarka Expressway                                              8
Sector 40                                                      8
New Colony                                                     7
Mianwali Colony                                                7
sector 58                                                      7
Sector 51                                                      7
Surat Nagar 1                                                  7
Sector 36 Sohna                                                7
Sector 11                                                      7
Sector 26                                                      7
Rajiv Nagar                                                    6
Ashok Vihar                                                    6
Sector 5                                                       6
Sector 1                                                       6
Jyoti Park                                                     6
Jacobpura                                                      6
New Palam Vihar                                                5
Chakkarpur                                                     5
Sector 2                                                       5
Sector 9                                                       5
Sector 23A                                                     5
Greenwood City                                                 5
Ansal Plaza                                                    5
Sector 80                                                      5
Arjun Nagar                                                    5
Sector 28                                                      5
Manesar                                                        5
Subhash Nagar                                                  5
Sushant Lok Phase 2                                            5
Saraswati Vihar                                                5
Dayanand Colony                                                5
Sector 30                                                      5
Sector 105                                                     5
Shivaji Nagar                                                  4
Surya Vihar                                                    4
Devilal Colony                                                 4
Sector 12A                                                     4
Shivpuri                                                       4
Sector 3A                                                      4
Dharam Colony                                                  4
Bhondsi                                                        4
Krishna Colony                                                 4
Madanpuri                                                      4
IMT Manesar                                                    4
Bhim Nagar                                                     4
Sector 36                                                      4
Adarsh Nagar                                                   4
Ravi Nagar                                                     4
Sector 6                                                       4
Suncity                                                        4
New                                                            4
Baldev Nagar                                                   4
Sector 45                                                      4
Garhi Harsaru                                                  4
Vishnu Garden                                                  4
Sector 12                                                      4
Valley View Estate                                             4
Sector 17                                                      4
Prem Nagar                                                     3
Gandhi Nagar                                                   3
Sector 73                                                      3
Laxmi Garden                                                   3
Sector 27                                                      3
Maruti Kunj                                                    3
Sector 17B                                                     3
MG Road                                                        3
Sector 8                                                       3
Patel Nagar                                                    3
Sector 15                                                      3
Sector 110 A                                                   3
Sector 88B                                                     3
B Block Sushant Lok Phase 1                                    3
Sector 17A                                                     3
Shakti Nagar                                                   3
A Block Sushant Lok Phase 1                                    3
Sector 23                                                      3
Sector 15 Part 1                                               2
Sector 15 Part 2                                               2
Sector 21                                                      2
Surat Nagar Phase 2                                            2
Sohna  Road                                                    2
IFFCO Chowk                                                    2
Sector 32                                                      2
Shankar Vihar                                                  2
Sector-11 sohna                                                2
Golf Course Ext Road                                           2
Lajpat Nagar                                                   2
Sector-2 Sohna                                                 2
Manohar Nagar                                                  2
Bhawani Enclave                                                2
Block A Surya Vihar                                            2
Sheetla Colony                                                 2
 Faridabad Road                                                2
Rajiv Chowk                                                    2
, Delhi NCR                                                    2
Bissar                                                         2
Rosewood                                                       2
Mohan Nagar                                                    2
Hira Nagar                                                     2
Sector 41                                                      2
Golf Course Road                                               2
New Basti                                                      2
Ambience Island                                                2
New Palam Vihar Phase 1                                        2
Acharya Puri                                                   2
Surat Nagar                                                    2
Shanti Nagar                                                   2
Nars                                                           2
Sushant Lok                                                    2
West Rajiv Nagar                                               2
Daulatabad                                                     2
New Palam Vihar Phase 2                                        2
Samaspur                                                       2
Pratap Nagar                                                   2
Farukhnagar                                                    2
Sector 24                                                      2
Sispal Vihar                                                   2
Mayfield Garden                                                2
B1 Block Sector 57                                             1
URBAN ESTATE, SECTOR 5                                         1
Damdma                                                         1
Sector 21A Faridabad                                           1
Anand Garden, Sector-105                                       1
V Block DLF Phase 3                                            1
near sector 1 market                                           1
sector-5 sheetla colony                                        1
Sadar Bazar                                                    1
Gopal Nagar, Garhi Ghasita, Sonipat                            1
Ram Nagar                                                      1
Rajiv Colony                                                   1
Sai Kunj                                                       1
HUDA Saraswati Vihar                                           1
G block DLF City Phase 1                                       1
Block G Sector-57                                              1
Naharpur Rupa                                                  1
Part 3 Sector 5                                                1
Bhimgarh Kheri Phase 3                                         1
Park View                                                      1
devi lal colony gali no 12 gurgaon nr omkar public school      1
Kheri                                                          1
Ansal's Palam Vihar                                            1
Om Nagar                                                       1
Alipur                                                         1
Mahavir pura                                                   1
ats marigold                                                   1
South City                                                     1
Shivji Park Colony                                             1
Near Pataudi Chowk                                             1
Rattan Garden                                                  1
Near euro                                                      1
New Jyoti Park                                                 1
Pataudi Road                                                   1
Sec 3 Bhim Vihar Part 1 Bhimgher Kheri                         1
Sector-7 Hous                                                  1
Ashok Vihar Phase I                                            1
Sector 9B                                                      1
old delhi road, opp sector-14                                  1
Hno 13 Sagar enclave Sura                                      1
Begampur Khatola                                               1
Saraswati Enclave                                              1
Sector 13                                                      1
Sector 37B                                                     1
Jat Colony,Fazilpur/Taj Nagar Road                             1
Sector 5 chowk                                                 1
New Colony, Sector 7                                           1
Sultanpur                                                      1
ravi nager basai road                                          1
Kanahi                                                         1
Godrej Aria , sector 79 ,                                      1
Tekchand Nagar                                                 1
Block H Ashok Vihar Phase III Extension                        1
Jacobpura Near Sadar Bazar                                     1
Heritage City                                                  1
Garauli Kalan                                                  1
Nirvana country Pocket H                                       1
Cyber City                                                     1
BPTP                                                           1
Vir Nagar                                                      1
Sector 17C                                                     1
Khandsa                                                        1
Laxman Vihar, Railway Road,                                    1
Sector-5 Sohna                                                 1
Bhora Kalan                                                    1
Civil L                                                        1
saroop garden rajendra park                                    1
Udyog Vihar Phase 1                                            1
Ashok Vihar Phase 3                                            1
laxmna vihar, phase 2                                          1
near nand hospital                                             1
Hsiidc Plot Sector 1 Imt Manesar                               1
Sector 37A                                                     1
Sector 4 Urban Estate                                          1
Dhankot                                                        1
Carterpuri Village                                             1
Near Khandsa Road                                              1
Sector-35 Sohna                                                1
Sector 42                                                      1
Lucknow                                                        1
Mahalaxmi Garden, Rajendra Place                               1
Name: count, dtype: int64

In [91]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip().str.lower())

In [92]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 Bedroom House for sale in Sector 4 Gurgaon,house,independent,sector 4,3.25,14444.0,2250.0,Plot area 250(209.03 sq.m.),3,3,2,not available,"Sector 4 Gurgaon, Gurgaon, Haryana",2.0,South-East,10+ Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Prat...",250 square yards east facing single story made...,"['30 Light', 'No AC', 'No Bed', 'No Chimney', ...","['Feng Shui / Vaastu Compliant', 'Park', 'Visi...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1,4 BHK Flat in Sector 67 Gurgaon,flat,bestech park view spa next,sector 67,2.70,11489.0,2350.0,Super Built up area 2350(218.32 sq.m.),4,4,3+,"pooja room,servant room","Middle Floor, Sector 67 Gurgaon, Gurgaon, Haryana",9.0,South-West,5 to 10 Year Old,"['Omaxe City Centre Mall', 'Golf Course Extens...",Located in the popular residential address of ...,"['4 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Security / Fire...","['Green Area5 out of 5', 'Construction4 out of..."
2,4 Bedroom House for sale in Sector 109 Gurgaon,house,international city by sobha phase 1,sector 109,6.75,10838.0,6228.0,Plot area 692(578.6 sq.m.),4,4,3+,"servant room,pooja room","Sector 109 Gurgaon, Gurgaon, Haryana",2.0,North-East,0 to 1 Year Old,"['Dwarka sector 21 metro station', 'Pacific D2...",International city is an urban enclave of vill...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Safety4.5 out of 5'..."
3,2 BHK Flat in Sohna,flat,hcbs sports ville,sohna,0.38,5067.0,750.0,Built Up area: 750 (69.68 sq.m.)Carpet area: 6...,2,2,2,not available,"Sohna, Sohna, Gurgaon, Haryana",9.0,East,undefined,"['The roadside cafe', 'GD Goenka Mess', 'ROyal...",Best in class property available at sohna loca...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area4 out of 5', 'Amenities4 out of 5'..."
4,2 BHK Flat in Sector 74 Gurgaon,flat,m3m skywalk,sector 74,1.78,12500.0,1424.0,Carpet area: 1424 (132.29 sq.m.),2,2,3+,not available,"Sector 74, Delhi Gurgaon Expressway, Sector 74...",12.0,NaN,undefined,"['Omaxe Gurgaon Mall', 'Omaxe Celebration Mall...",Best in class property available at sector 74 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN

In [93]:
(df['sector'].str.lower().str.contains('sector')).sum()

np.int64(3018)

In [94]:
(df['address'].str.lower().str.contains('sector')).sum()

3077

In [95]:
a=(~(df['sector'].str.lower().str.contains('sector')))&(df['address'].str.lower().str.contains('sector',na=False))
a.sum()

np.int64(65)

In [96]:
df[a]

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
17,3 Bedroom House for sale in Sohna Road,house,independent,sohna road,5.50,5093.0,10799.0,Plot area 1200(1003.35 sq.m.)Built Up area: 35...,3,3,3+,"pooja room,study room,servant room,others","Sector 63a, Sohna Road, Gurgaon, Haryana",2.0,West,5 to 10 Year Old,"['Kamal Hospital and Maternity Centre', 'Gobin...",Three bedroom villa in the most serene area. W...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
80,2 BHK Flat in Sohna,flat,trisara our homes 3,sohna,0.40,4478.0,893.0,Built Up area: 900 (83.61 sq.m.)Carpet area: 6...,2,2,2,not available,"Sohna Sector 6, Sohna, Gurgaon, Haryana",1.0,NaN,undefined,"['Metro Station', 'Gyanchand Market', 'Rajiv C...",Best in class property available at sector 6 s...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
135,6 Bedroom House for sale in Prem Nagar,house,independent,prem nagar,0.62,32291.0,192.0,Built Up area: 192 (17.84 sq.m.),6,6,0,not available,"Prem Nagar, Sector 11, Prem Nagar, Gurgaon, Ha...",3.0,NaN,undefined,NaN,This residential house is built over 3 floors....,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
147,2 Bedroom House for sale in Rajendra Park,house,independent,rajendra park,9.90,49500.0,2000.0,Built Up area: 2000 (185.81 sq.m.)Carpet area:...,2,2,2,not available,"Mahalaxmi Garden Part-1, Rajendera Park, Secto...",3.0,North,undefined,"['Palam Vihar Vyapar kendra', 'Chintapurni Man...","2 bath, semi-Furnished, ground floor (Of 3), n...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
190,2 Bedroom House for sale in Devilal Colony,house,independent,devilal colony,0.22,7407.0,297.0,Carpet area: 33 (27.59 sq.m.),2,2,2,not available,"Devilal Colony, Sector 9, Basai Road, Devilal ...",1.0,NaN,undefined,NaN,Best in class property available at devilal co...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
208,6 Bedroom House for sale in Rajendra Park,house,independent,rajendra park,1.10,12222.0,900.0,Carpet area: 900 (83.61 sq.m.),6,4,1,not available,"Rajendra Park, Sector 105, Rajendra Park, Gurg...",1.0,South-West,undefined,NaN,Best in class property available at rajendra p...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
232,2 Bedroom House for sale in Baldev Nagar,house,independent,baldev nagar,0.53,5888.0,900.0,Built Up area: 900 (83.61 sq.m.),2,2,0,not available,"Baldev Nagar, Sector 9, Baldev Nagar, Gurgaon,...",1.0,NaN,undefined,NaN,A 2 storeyed residential house is located in b...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
246,3 Bedroom House for sale in Laxman Vihar,house,independent,laxman vihar,0.85,7522.0,1130.0,Built Up area: 1130 (104.98 sq.m.),3,3,0,not available,"Laxman Vihar Industrial Area, Sector 3a, Laxma...",1.0,NaN,undefined,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",A residential house is available for sale. It ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
359,3 Bedroom House for sale in Baldev Nagar,house,independent,baldev nagar,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),3,2,0,not available,"Baldev Nagar, Sector 9, Baldev Nagar, Gurgaon,...",1.0,NaN,undefined,"['Ankur Clinic and Maternity Home', 'Navjeevan...",Villa is available for sale. It carpet area of...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
477,3 Bedroom House for sale in Park View,house,ansal esencia sovereign floors,park view,1.05,7075.0,1484.0,Built Up area: 1484 (137.87 sq.m.)Carpet area:...,3,3,3,not available,Ansal Esencia Sovereign Floors Sector 67 Golf ...,3.0,South-East,undefined,"['Sri Radhe Krishna Temple', 'Kamal Hospital a...",3bhk penthouse for new property in ansal esenc...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
518,2 Bedroom House for sale in Shivpuri,house,independent,shivpuri,2.00,11111.0,1800.0,Plot area 200(167.23 sq.m.),2,2,1,not available,"Gurgaon Sector -7, Shivpuri, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Arya...",Interested to sell independent house/villa.Pla...,"['2 Fan', 'No AC', 'No Bed', 'No Chimney', 'No...",NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."
543,10 Bedroom House for sale in DLF Phase 4,house,dlf city plot phase 4,dlf phase 4,13.00,1992.0,65261.0,Carpet area: 7250 (6061.92 sq.m.),10,10,3+,not available,"Dlf City Phase 4, Sector 28, DLF Phase 4, Gurg...",1.0,NaN,undefined,"['Dlf phase 1 metro station', 'Huda city centr...",Best in class property available at dlf city p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
704,6 Bedroom House for sale in Nirvana Country,house,independent,nirvana country,13.20,27155.0,4861.0,Built Up area: 4861 (451.6 sq.m.),6,6,0,not available,"Nirvana Country, Sector 50, Nirvana Country, G...",2.0,NaN,undefined,NaN,6bhk residential house for resale in nirvana c...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
880,2 Bedroom House for sale in Rajendra Park,house,independent,rajendra park,0.38,76000.0,50.0,Carpet area: 50 (4.65 sq.m.),2,2,2,not available,"Rajendra Park Block G, Sector 105, Rajendra Pa...",1.0,NaN,undefined,NaN,Best in class property available at rajendra p...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
948,2 BHK Flat in Sohna,flat,eldeco accolade,sohna,0.95,6178.0,1538.0,Super Built up area 1457(135.36 sq.m.)Built Up...,2,2,3+,"study room,others","Sohna-Gurgaon Road, Sector 2, Near G.D Goenka ...",8.0,South,Under Construction,"['Global City Centre', 'Sohna Road', 'Damdama ...",The property is a 2bhk+2toilet+study room faci...,[],"['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Management4 out of 5', 'Green Area5 out of 5..."
1016,3 BHK Flat in Dwarka Expressway Gurgaon,flat,experion heartsong,dwarka expressway,1.08,6150.0,1756.0,Built Up area: 1758 (163.32 sq.m.),3,3,0,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
1023,1 Bedroom House for sale in Mianwali Colony,house,project mianwali colony,mianwali colony,1.70,9444.0,1800.0,Carpet area: 1800 (167.23 sq.m.),1,1,2,not available,"Mianwali Colony, Sector 12a, Mianwali Colony, ...",1.0,NaN,undefined,"['Hanuman Mandir', 'Sheetla Mata Mandir', 'Lal...",Best in class property available at mianwali c...,NaN,NaN,"['Environment3.5 out of 5', 'Lifestyle4 out of..."
1040,2 BHK Flat in Sohna,flat,signature global park,sohna,0.65,7299.0,891.0,Built Up area: 822 (76.37 sq.m.)Carpet area: 5...,2,2,3,not available,"Signature Global Park, Sohna Sector 36, Near D...",1.0,NaN,0 to 1 Year Old,"['Sector 55-56 metro', 'Global city centre', '...",2bhk multistorey apartment for new property in...,NaN,NaN,"['Management4 out of 5', 'Green Area5 out of 5..."
1048,2 BHK Flat in Sohna,flat,signature global park,sohna,0.55,6690.0,822.0,Carpet area: 822 (76.37 sq.m.),2,2,3,not available,"Sohna Sector 36, Sohna, Gurgaon, Haryana",3.0,East,undefined,"['Sector 55-56 metro', 'Global city centre', '...",Best in class property available at sector 36 ...,NaN,NaN,"['Green Area5 out of 5', 'Construction5 out of..."
1157,2 BHK Flat in Sohna,flat,gls arawali homes,sohna,0.30,5291.0,567.0,Built Up area: 567 (52.68 sq.m.),2,2,0,not available,"Sohna Sector 4, Sohna, Gurgaon, Haryana",10.0,NaN,undefined,"['Huda City Centre', 'Golf Course Road', 'Delh...",2bhk multistorey apartment for resale in gls a...,NaN,NaN,"['Management4 out of 5', 'Green Area5 out of 5..."
1270,5 Bedroom House for sale in Nirvana Country,house,unitech espace,nirvana country,11.50,35494.0,3240.0,Built Up area: 3240 (301.01 sq.m.),5,6,0,not available,"Sector 50, Nirvana Country, Gurgaon, Haryana",1.0,North-West,undefined,"['Sri Radhe Krishna Temple', 'Standard charter...",Best in class property available at sector 50 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
1319,2 BHK Flat in Sohna,flat,mvn athens,sohna,0.25,5198.0,481.0,Built Up area: 481 (44.69 sq.m.),2,2,0,not available,"Sohna Sector 5, Sohna, Gurgaon, Haryana",0.0,NaN,1 to 5 Year Old,"['SBI ATM', 'Axis bank ATM', 'UCO bank ATM', '...",Best in class property available at sector 5 s...,"['3 Fan', '5 Light', '1 Modular Kitchen', 'No ...","['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Green Area4 out of 5', 'Construction4 out of..."
1367,3 Bedroom House for sale in Rajendra Park,house,independent,rajendra park,1.15,3285.0,3501.0,Carpet area: 3500 (325.16 sq.m.),3,2,1,not available,"Rajendra Park Block B, Sector 105, Rajendra Pa...",1.0,NaN,undefined,NaN,Best in class property available at rajendra p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1493,3 Bedroom House for sale in Laxman Vihar,house,independent,laxman vihar,0.70,6648.0,1053.0,Built Up area: 117 (97.83 sq.m.),3,3,0,not available,"Laxman Vihar, Sector 3a, Laxman Vihar, Gurgaon...",1.0,NaN,undefined,NaN,3bhk residential house for resale in laxman vi...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1536,5 Bedroom House for sale in Gandhi Nagar,house,independent,gandhi nagar,0.45,90000.0,50.0,Built Up area: 50 (4.65 sq.m.),5,3,0,not available,"Gandhi Nagar, Sector 11, Gandhi Nagar, Gurgaon...",1.0,NaN,undefined,NaN,Best in class property available at gandhi nag...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1557,2 BHK Flat in Sohna,flat,gls arawali homes,sohna,0.32,6722.0,476.0,Built Up area: 476 (44.22 sq.m.),2,1,0,not available,"Gls Arawali Homes, Sector 4, Gurgaon, Sohna, G...",0.0,NaN,undefined,"['Huda City Centre', 'Golf Course Road', 'Delh...","Property for sale in sector 4, gurgaon. This 2...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area5 out of 5', 'Construction4 out of..."
1685,4 Bedroom House for sale in Jyoti Park,house,independent,jyoti park,1.35,40909.0,330.0,Built Up area: 330 (30.66 sq.m.),4,5,0,not available,"Jyoti Park, Sector 7, Jyoti Park, Gurgaon, Har...",3.0,NaN,undefined,NaN,"5 bath, furnished, ground floor (Of 3), jyoti ...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1700,3 Bedroom House for sale in Gandhi Nagar,house,independent,gandhi nagar,1.45,8000.0,1812.0,Built Up area: 1800 (167.23 sq.m.)Carpet area:...,3,2,1,not available,68/179 Gali No 10 Gandhi Nagar Sector 11 Near ...,1.0,North,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'Ka...",3bhk residential house for sale. 68/179 gali n...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1717,2 Bedroom House for sale in Arjun Nagar,house,independent,arjun nagar,0.32,7111.0,450.0,Built Up area: 450 (41.81 sq.m.)Carpet area: 3...,2,3,1,not available,"Arjun Nagar, Sector 8, Arjun Nagar, Gurgaon, H...",1.0,North-East,1 to 5 Year Old,NaN,Best in class property available at arjun naga...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1738,1 BHK Flat in Sispal Vihar,flat,element one service,sispal vihar,1.00,11765.0,850.0,Built Up area: 850 (78.97 sq.m.)Carpet area: 6...,1,1,1,not available,"Sispal Vihar, Sector 49, Sohna Road, Sispal Vi...",8.0,North-East,undefined,"['Standard chartered ATM', 'Icici bank ATM', '...",The apartments are priced attractively at 1300...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
1745,4 Bedroom House for sale in Saraswati Vihar,house,project housing board colony,saraswati vihar,2.58,17695.0,1458.0,Carpet area: 1300 (120.77 sq.m.),4,2,2,not available,"Saraswati Vihar, Sector 28, Saraswati Vihar, G...",2.0,NaN,undefined,"['Iffco chowk metro station', 'Citi bank ATM',...",Best in class property available at saraswati ...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."
1774,2 BHK Flat in Sohna,flat,trisara our homes 3,sohna,0.38,6312.0,602.0,Built Up area: 602 (55.93 sq.m.),2,2,2,not available,"Sohna Sector 6, Sohna, Gurgaon, Haryana",1.0,NaN,undefined,"['Metro Station', 'Gyanchand Market', 'Rajiv C...",Best in class property available at sector 6 s...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
1788,4 BHK Flat in Adarsh Nagar,flat,lord krishna,adarsh nagar,2.70,8571.0,3150.0,Built Up area: 3150 (292.64 sq.m.),4,3,3,not available,"Adarsh Nagar, Sector 12a, Adarsh Nagar, Gurgao...",6.0,North-East,undefined,"['Huda city centre metro station', 'Hanuman Ma...",This 4 bhk flat is located in lord krishna cgh...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
1818,5 Bedroom House for sale in Nirvana Country,house,unitech escape,nirvana country,12.00,37037.0,3240.0,Carpet area: 360 (301.01 sq.m.),5,6,3+,not available,"Nirvana Country, Sector 50, Nirvana Country, G...",3.0,East,undefined,"['Sector 55-56 Metro Station', 'Airia Mall', '...",5bhk villa for resale in unitech escape at nir...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
1828,6 Bedroom House for sale in Bhim Nagar,house,independent,bhim nagar,1.00,41666.0,240.0,Built Up area: 240 (22.3 sq.m.),6,4,0,not available,"Bhim Nagar, Sector 6, Bhim Nagar, Gurgaon, Har...",3.0,NaN,undefined,NaN,Best in class property available at bhim nagar...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
1842,3 Bedroom House for sale in Sohna,house,signature global park,sohna,0.85,7589.0,1120.0,Built Up area: 1120 (104.05 sq.m.),3,2,2,not available,"Signature Global Park 4 Phase Ii, Sector 36 So...",1.0,NaN,Jun 2024,"['Sector 55-56 metro', 'Global city centre', '...",Property is park facing with plc. Corner and p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1878,2 BHK Flat in Sohna,flat,mvn athens,sohna,0.25,5189.0,482.0,Carpet area: 481.73 (44.75 sq.m.),2,2,1,pooja room,"Sector 5, Sohna, Gurgaon, Haryana",0.0,North,1 to 5 Year Old,"['SBI ATM', 'Axis bank ATM', 'UCO bank ATM', '...","1 or 2bhk with all aminities,parking,play ground",NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Management5 out of 5', 'Green Area4 out of 5..."
1965,4 Bedroom House for sale in Rajendra Park,house,independent,rajendra park,0.55,98214.0,56.0,Built Up area: 56 (5.2 sq.m.),4,4,0,not available,"Rajendra Park, Sector 105, Rajendra Park, Gurg...",2.0,NaN,undefined,NaN,Best in class property available at rajendra p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2006,4 Bedroom House for sale in Jacobpura,house,independent,jacobpura,1.20,14184.0,846.0,Plot area 846(78.6 sq.m.)Built Up area: 846 sq...,4,4,2,pooja room,"Jacobpura, Sector 12, Gurgaon, Jacobpura, Gurg...",2.0,North,1 to 5 Year Old,"['Hanuman Mandir', 'Rajiv Memorial Eye Infirma...","4 bhk independent house, 2 drawing rooms, 4 ba...","['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...",['Visitor Parking'],"['Environment3 out of 5', 'Lifestyle4 out of 5..."
2059,10 Bedroom House for sale in Rajiv Nagar,house,independent,rajiv nagar,2.25,6944.0,3240.0,Carpet area: 360 (301.01 sq.m.),10,10,2,not available,"Rajiv Nagar, Sector 13, Rajiv Nagar, Gurgaon, ...",1.0,East,undefined,NaN,36 room with attached bathroom and kitchen raj...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
2210,3 Bedroom House for sale in Arjun Nagar,house,independent,arjun nagar,0.62,11273.0,550.0,Built Up area: 550 (51.1 sq.m.),3,1,0,not available,"Arjun Nagar, Sector 8, Arjun Nagar, Gurgaon, H...",2.0,NaN,undefined,NaN,Best in class property available at arjun naga...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2225,3 Bedroom House for sale in Rajendra Park,house,independent,rajendra park,1.30,11556.0,1125.0,Built Up area: 1125 (104.52 sq.m.),3,3,1,not available,"Rajendra Park Block G, Sector 105, Rajendra Pa...",1.0,East,undefined,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Best in class property available at rajendra p...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2257,1 BHK Flat in Sohna,flat,trisara our homes 3,sohna,0.21,4339.0,484.0,Built Up area: 484 (44.97 sq.m.),1,1,0,not available,"Sohna Sector 6, Sohna, Gurgaon, Haryana",2.0,NaN,undefined,"['Metro Station', 'Gyanchand Market', 'Rajiv C...",Best in class property available at sector 6 s...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
2624,3 BHK Flat in Sohna,flat,signature global park,sohna,0.90,8036.0,1120.0,Built Up area: 1120 (104.05 sq.m.),3,2,0,not available,"Sohna Sector 36, Sohna, Gurgaon, Haryana",2.0,NaN,Mar-24,"['Sector 55-56 metro', 'Global city centre', '...",Best in class property available at sector 36 ...,NaN,NaN,"['Green Area5 out of 5', 'Amenities5 out of 5'..."
2654,5 Bedroom House for sale in Ravi Nagar,house,independent,ravi nagar,0.42,9333.0,450.0,Built Up area: 450 (41.81 sq.m.),5,3,2,not available,"Ravi Nagar, Sector 9, Ravi Nagar, Gurgaon, Har...",2.0,NaN,undefined,"['State bank ATM', 'Ankur Clinic and Maternity...",Best in class property available at ravi nagar...,NaN,NaN,NaN
2680,2 Bedroom House for sale in Vishnu Garden,house,independent,vishnu garden,0.35,7778.0,450.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"Vishnu Garden, Sector 105, Vishnu Garden, Gurg...",2.0,East,undefined,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Best in class property available at vishnu gar...,NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
2713,5 Bedroom House for sale in Jyoti Park,house,independent,jyoti park,1.16,11717.0,990.0,Carpet area: 110 (91.97 sq.m.),5,4,2,not available,"Jyoti Park, Sector 7, Jyoti Park, Gurgaon, Har...",1.0,North-East,undefined,NaN,"Square plot, airy atmosphere, property ventila...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2765,5 Bedroom House for sale in Laxman Vihar,house,independent,laxman vihar,0.50,10482.0,477.0,Built Up area: 53 (44.31 sq.m.),5,3,0,not available,"Laxman Vihar, Sector 3a, Laxman Vihar, Gurgaon...",1.0,NaN,undefined,NaN,5bhk residential house for resale in laxman vi...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2837,5 Bedroom House for sale in Jyoti Park,house,independent,jyoti park,1.20,11194.0,1072.0,Built Up area: 1072 (99.59 sq.m.),5,4,2,not available,"Jyoti Park, Sector 7, Jyoti Park, Gurgaon, Har...",3.0,NaN,undefined,"['State bank ATM', 'Dr. Madan Clinic', 'Taneja...",5bhk residential house for resale in jyoti par...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2853,3 Bedroom House for sale in Devilal Colony,house,independent,devilal colony,0.50,6083.0,822.0,Built Up area: 822 (76.37 sq.m.)Carpet area: 7...,3,2,1,not available,"Devilal Colony, Sector 9, Basai Road, Devilal ...",1.0,NaN,undefined,NaN,"West facing, having submersible installed. Car...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [97]:
import re
b=df[a]['address'].str.lower().str.extract(r'sector\s*-?\s*(\d+)')
b

        0
17     63
80      6
135    11
147   105
190     9
208   105
232     9
246     3
359     9
477    67
518     7
543    28
704    50
880   105
948     2
1016  108
1023   12
1040   36
1048   36
1157    4
1270   50
1319    5
1367  105
1493    3
1536   11
1557    4
1685    7
1700   11
1717    8
1738   49
1745   28
1774    6
1788   12
1818   50
1828    6
1842   36
1878    5
1965  105
2006   12
2059   13
2210    8
2225  105
2257    6
2624   36
2654    9
2680  105
2713    7
2765    3
2837    7
2853    9
2929   28
2944    5
3046   13
3131  105
3257  105
3292  105
3295   36
3350    3
3446    3
3484   12
3522   49
3637  103
3749    7
3768   36
3896   36

In [98]:
b.isnull().sum()

0    0
dtype: int64

In [99]:
df.loc[a,'sector']='sector ' + b[0]

In [100]:
df.sample(5)

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
3532,3 BHK Flat in Sector 83 Gurgaon,flat,emaar palm gardens,sector 83,1.55,9011.0,1720.0,Super Built up area 1720(159.79 sq.m.)Built Up...,3,3,3,servant room,"804, Sector 83 Gurgaon, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"[""V'Lante Mall"", 'NH 48 Gurugram', 'iGrow Mont...",Check out this 3 bhk apartment for sale in ema...,"['3 Wardrobe', '1 Exhaust Fan', '3 Geyser', '1...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
1795,12 Bedroom House for sale in Mehrauli Gurgaon ...,house,independent,mehrauli road,8.00,17707.0,4518.0,Plot area 502(419.74 sq.m.),12,4,3+,"servant room,store room","Mehrauli Gurgaon Road, Gurgaon, Haryana",3.0,North,10+ Year Old,"['Mg road metro station', 'Iffco chowk metro s...",Its north and park facing. Main iffco chowk wa...,"['1 Wardrobe', '1 Fan', '5 Light', '1 AC', 'No...","['High Ceiling Height', 'Water Storage', 'No o...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1891,8 Bedroom House for sale in Manesar,house,independent,manesar,1.10,6172.0,1782.0,Plot area 1782(165.55 sq.m.),8,8,0,not available,"Manesar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Dr. Sahil Clinic', 'Pooja Clinic', 'Yadav De...",Building for rent purpose \n27k rent \n8 rooms...,[],NaN,"['Environment4 out of 5', 'Lifestyle3.5 out of..."
129,2 BHK Flat in Sector 67A Gurgaon,flat,pyramid urban,sector 67a,0.70,11844.0,591.0,Carpet area: 591 (54.91 sq.m.),2,2,1,not available,"Sector 67A Gurgaon, Gurgaon, Haryana",14.0,North,0 to 1 Year Old,"['Airia Mall, Sector 68', 'M3M Cosmopolitan Ma...",This is on road property sector 67a.,"['3 Fan', '2 Geyser', '4 Light', '1 Chimney', ...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1266,3 BHK Flat in Sector 60 Gurgaon,flat,ireo skyon,sector 60,2.82,12818.0,2200.0,Super Built up area 2403(223.25 sq.m.)Built Up...,3,3,3,servant room,"203, Sector 60 Gurgaon, Gurgaon, Haryana",2.0,South-East,1 to 5 Year Old,"['Sector 55-56 Metro', 'Golf Course Extension'...",Looking for a 3 bhk property for sale in gurga...,"['1 Water Purifier', '4 Fan', '1 Geyser', '14 ...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."

In [101]:
df['sector'].value_counts()

sector
sohna                                                        147
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 90                                                     90
sector 65                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    60
sector 56                                                     57
sector 95                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
sector 70                                                     53
sector 37c                                                    53
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
nirvana country                                               50
sector 67                                                     49
sector 66                                                     46
sector 103                                                    46
sector 113                                                    43
dlf phase 1                                                   43
dlf phase 2                                                   43
sector 61                                                     42
sector 82                                                     42
sector 49                                                     38
sector 106                                                    38
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 54                                                     27
sector 71                                                     27
dlf phase 4                                                   24
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 67a                                                    22
laxman vihar                                                  22
sector 111                                                    22
dlf phase 3                                                   22
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 3                                                      19
sector 74                                                     18
sector 63a                                                    18
sector 62                                                     17
sector 91                                                     17
sushant lok phase 3                                           16
sector 99                                                     16
sector 63                                                     16
sector 110                                                    16
sector 60                                                     15
sector 105                                                    15
sector 7                                                      15
sector 14                                                     15
sector 50                                                     15
sector 76                                                     14
sector 52                                                     14
sector 53                                                     14
gwal pahari                                                   14
dlf phase 5                                                   14
sector 1 imt manesar                                          14
sector 46                                                     13
sector 36a                                                    13
laxman vihar phase 2                                          13
sector 31                                                     12
uppals southend                                               12
sector 38                                                     12
sector 39                                                     12
sector 93                                                     11
sector 9a                                                     11
sector 4                                                      11
ashok vihar phase 3 extension                                 11
sector 47                                                     11
sohna road                                                    11
sector 36                                                     11
sector 1a imt manesar                                         10
sector 11                                                     10
sector 9                                                      10
south city 1                                                   9
ashok vihar phase 2                                            9
sector 55                                                      9
sector 5                                                       9
sector 95a                                                     9
sector 59                                                      8
malibu town                                                    8
palam vihar extension                                          8
sector 12                                                      8
sector 40                                                      8
c block sushant lok phase 1                                    8
sector 10a                                                     8
sector 6                                                       8
sector 89 a                                                    8
sector 43                                                      8
sector 28                                                      8
mehrauli  road                                                 8
sector 57                                                      8
rajendra park                                                  7
sector 58                                                      7
surat nagar 1                                                  7
sector 26                                                      7
sector 51                                                      7
sector 36 sohna                                                7
ashok vihar                                                    6
dwarka expressway                                              6
mianwali colony                                                6
sector 1                                                       6
new colony                                                     6
sector 2                                                       6
manesar                                                        5
sector 8                                                       5
sushant lok phase 2                                            5
new palam vihar                                                5
ansal plaza                                                    5
sector 23a                                                     5
chakkarpur                                                     5
sector 80                                                      5
greenwood city                                                 5
sector 30                                                      5
dayanand colony                                                5
jacobpura                                                      5
garhi harsaru                                                  4
rajiv nagar                                                    4
sector 3a                                                      4
shivaji nagar                                                  4
saraswati vihar                                                4
imt manesar                                                    4
krishna colony                                                 4
suncity                                                        4
sector 45                                                      4
sector 12a                                                     4
surya vihar                                                    4
valley view estate                                             4
dharam colony                                                  4
madanpuri                                                      4
subhash nagar                                                  4
new                                                            4
bhondsi                                                        4
sector 17                                                      4
sector 23                                                      3
laxmi garden                                                   3
sector 17a                                                     3
maruti kunj                                                    3
arjun nagar                                                    3
sector 17b                                                     3
sector 13                                                      3
bhim nagar                                                     3
a block sushant lok phase 1                                    3
sector 73                                                      3
shivpuri                                                       3
sector 88b                                                     3
sector 27                                                      3
sector 110 a                                                   3
sector 15                                                      3
adarsh nagar                                                   3
shakti nagar                                                   3
b block sushant lok phase 1                                    3
ravi nagar                                                     3
patel nagar                                                    3
jyoti park                                                     3
mg road                                                        3
golf course ext road                                           2
sector 15 part 1                                               2
surat nagar phase 2                                            2
sector 32                                                      2
lajpat nagar                                                   2
sheetla colony                                                 2
manohar nagar                                                  2
block a surya vihar                                            2
hira nagar                                                     2
devilal colony                                                 2
mayfield garden                                                2
farukhnagar                                                    2
baldev nagar                                                   2
sector 15 part 2                                               2
shankar vihar                                                  2
sector-2 sohna                                                 2
faridabad road                                                 2
sector-11 sohna                                                2
, delhi ncr                                                    2
prem nagar                                                     2
bhawani enclave                                                2
ambience island                                                2
golf course road                                               2
sector 41                                                      2
new palam vihar phase 1                                        2
new basti                                                      2
acharya puri                                                   2
sector 21                                                      2
west rajiv nagar                                               2
rosewood                                                       2
nars                                                           2
sushant lok                                                    2
shanti nagar                                                   2
bissar                                                         2
iffco chowk                                                    2
sohna  road                                                    2
surat nagar                                                    2
rajiv chowk                                                    2
samaspur                                                       2
pratap nagar                                                   2
daulatabad                                                     2
new palam vihar phase 2                                        2
sector 24                                                      2
mohan nagar                                                    2
om nagar                                                       1
block g sector-57                                              1
near sector 1 market                                           1
v block dlf phase 3                                            1
anand garden, sector-105                                       1
sector 21a faridabad                                           1
damdma                                                         1
vishnu garden                                                  1
urban estate, sector 5                                         1
sadar bazar                                                    1
sai kunj                                                       1
laxmna vihar, phase 2                                          1
near nand hospital                                             1
naharpur rupa                                                  1
rajiv colony                                                   1
gopal nagar, garhi ghasita, sonipat                            1
huda saraswati vihar                                           1
bhimgarh kheri phase 3                                         1
part 3 sector 5                                                1
g block dlf city phase 1                                       1
ram nagar                                                      1
ansal's palam vihar                                            1
gandhi nagar                                                   1
b1 block sector 57                                             1
sector 9b                                                      1
sector-7 hous                                                  1
pataudi road                                                   1
shivji park colony                                             1
devi lal colony gali no 12 gurgaon nr omkar public school      1
near euro                                                      1
kheri                                                          1
rattan garden                                                  1
new jyoti park                                                 1
sec 3 bhim vihar part 1 bhimgher kheri                         1
ashok vihar phase i                                            1
begampur khatola                                               1
hno 13 sagar enclave sura                                      1
old delhi road, opp sector-14                                  1
south city                                                     1
near pataudi chowk                                             1
saraswati enclave                                              1
new colony, sector 7                                           1
sultanpur                                                      1
sector 5 chowk                                                 1
alipur                                                         1
mahavir pura                                                   1
ats marigold                                                   1
heritage city                                                  1
ravi nager basai road                                          1
bhora kalan                                                    1
kanahi                                                         1
godrej aria , sector 79 ,                                      1
tekchand nagar                                                 1
jacobpura near sadar bazar                                     1
block h ashok vihar phase iii extension                        1
garauli kalan                                                  1
sector 37b                                                     1
jat colony,fazilpur/taj nagar road                             1
cyber city                                                     1
bptp                                                           1
laxman vihar, railway road,                                    1
sector 17c                                                     1
vir nagar                                                      1
nirvana country pocket h                                       1
sector-5 sohna                                                 1
ashok vihar phase 3                                            1
civil l                                                        1
saroop garden rajendra park                                    1
khandsa                                                        1
udyog vihar phase 1                                            1
sector-5 sheetla colony                                        1
hsiidc plot sector 1 imt manesar                               1
sector 37a                                                     1
sector 4 urban estate                                          1
dhankot                                                        1
carterpuri village                                             1
near khandsa road                                              1
sector-35 sohna                                                1
sector 42                                                      1
lucknow                                                        1
mahalaxmi garden, rajendra place                               1
Name: count, dtype: int64

In [102]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [103]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [104]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [105]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [106]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [107]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [108]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [109]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [110]:
df['sector'].value_counts()

sector
sohna road                    147
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 81                      90
sector 90                      90
sector 65                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     60
sector 56                      57
sector 95                      57
sector 89                      56
sector 2                       56
sector 48                      56
sector 70a                     54
sector 70                      53
sector 37c                     53
sector 43                      53
sector 84                      51
sector-33 sohna road           51
sector 26                      50
sector 49                      50
sector 67                      49
sector 103                     46
sector 66                      46
sector 28                      45
sector 25                      43
sector 113                     43
sector 82                      42
sector 61                      42
sector 106                     38
sector 7                       37
sector 4                       33
sector 99a                     32
sector 54                      31
sector 12                      30
sector 68                      30
sector 72                      29
sector 77                      29
sector 71                      27
sector 3                       25
sector 11                      24
sector 24                      24
sector 112                     24
sector 57                      24
sector 88a                     23
sector 14                      23
sector 105                     23
sector 33                      23
sector 111                     22
sector 67a                     22
sector 82a                     20
sector 22                      20
sector 47                      19
sector 78                      19
gwal pahari                    18
sector 74                      18
sector 63a                     18
sector 91                      17
sector 62                      17
sector 63                      16
sector 99                      16
sector 110                     16
sector 6                       16
sector 60                      15
sector 9                       15
sector 52                      14
sector 76                      14
sector 55                      14
sector 1 manesar               14
sector 53                      14
sector 36a                     13
sector 4 phase 2               13
sector 46                      13
sector 38                      12
sector 31                      12
sector 39                      12
sector 41                      11
sohna road road                11
sector 9a                      11
sector 3 phase 3 extension     11
sector 36                      11
sector 93                      11
sector 1a manesar              10
manesar                         9
sector 45                       9
sector 5                        9
sector 3 phase 2                9
sector 13                       9
sector 95a                      9
sector 23                       8
sector 8                        8
c block sector 43               8
sector 10a                      8
sector 2 extension              8
sector 40                       8
sector 17                       8
sector 59                       8
sector 89 a                     8
sector 58                       7
sector 36 sohna road            7
sector 51                       7
sector 21                       6
dwarka expressway               6
sector 1                        6
new sector 2                    5
sector 80                       5
sector 30                       5
sector 23a                      5
sector 12a                      4
new                             4
sector 3a                       4
sector 110 a                    3
sector 88b                      3
sector 27                       3
sector 17a                      3
sector 73                       3
a block sector 43               3
b block sector 43               3
maruti kunj                     3
sector 17b                      3
patel nagar                     3
sector 15                       3
Name: count, dtype: int64

In [111]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [112]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')

In [113]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
81,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun-27,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
1475,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
1652,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
1800,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN

In [114]:
df.loc[81,'sector'] = 'sector 76'
df.loc[1475,'sector'] = 'sector 37'
df.loc[1652,'sector'] = 'sector 92'
df.loc[1800,'sector'] = 'sector 90'

In [115]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
475,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
1709,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
2861,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3331,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
3488,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [116]:
df.loc[[475,1709,2861,3331,3488],'sector']='sector 110'

In [117]:
df.drop(columns=['property_name','address','description','rating'],inplace=True)

In [118]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
3931,flat,experion windchants,sector 112,3.00,11538.0,2600.0,Super Built up area 2802(260.31 sq.m.)Built Up...,3,3,2,others,2.0,North,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","['5 Fan', '1 Exhaust Fan', '5 Geyser', '18 Lig...","['Feng Shui / Vaastu Compliant', 'Security / F..."
67,flat,emaar palm heights,sector 77,2.25,11250.0,2000.0,Super Built up area 2000(185.81 sq.m.),3,3,3,servant room,22.0,NaN,0 to 1 Year Old,"['DLF Cyber City', 'Vatika Town Square', ""St. ...","['1 Geyser', '1 Stove', '1 Chimney', '5 AC', '...","['Power Back-up', 'Feng Shui / Vaastu Complian..."
2979,flat,dlf regency park,sector 28,1.24,12400.0,1000.0,Super Built up area 1150(106.84 sq.m.)Built Up...,2,2,3+,pooja room,19.0,South,5 to 10 Year Old,"['Sector 42-43 metro station', 'Dlf phase 1 me...","['2 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...","['Centrally Air Conditioned', 'Water purifier'..."
2048,house,nirvana cedar crest,sector 50,3.99,8866.0,4500.0,Plot area 4500(418.06 sq.m.),4,5,3+,"pooja room,servant room",4.0,North-East,0 to 1 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...","['4 Geyser', '9 Light', '1 AC', '1 Modular Kit...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
1406,flat,ats kocoon,sector 109,2.95,10350.0,2850.0,Built Up area: 3150 (292.64 sq.m.)Carpet area:...,4,4,3+,"store room,servant room",7.0,South-East,1 to 5 Year Old,"['Jagdish Super Market', 'Dwarka', 'Euro Inter...","['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '22 L...","['Centrally Air Conditioned', 'Security / Fire..."

In [119]:
df.duplicated().sum()

np.int64(123)

In [120]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)