In [62]:
import numpy as np
import pandas as pd

In [63]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [64]:
df=pd.read_csv('flats.csv')
df.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
3003,3 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Raheja Sampada,90 Lac,"₹ 6,569/sq.ft.",Super Built up area 1370(127.28 sq.m.),3 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sector 92 Gurgaon, Gurgaon, Haryana",11st of 14 Floors,East,1 to 5 Year Old,"['Sapphire 93', 'JMS crosswalk', 'Reliance Sma...",We are the proud owners of this 3 bhk apartmen...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Safety3 out of 5', 'Lifestyle4 out of 5', 'E...",I56902148
1466,3 BHK Flat in Sector 81 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Bestech Park View Grand Spa4.3 ★,2.29 Crore,"₹ 8,609/sq.ft.",Super Built up area 2660(247.12 sq.m.)Carpet a...,3 Bedrooms,4 Bathrooms,3+ Balconies,"Servant Room,Study Room","10th Floor Bestech Grand Spa, Sector 81 Gurgao...",10th of 29 Floors,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, IMT Manesar', 'Dwa...",Very urgent sale \nIts a 3bhk+servant+family l...,"['4 Wardrobe', '4 Fan', '1 Fridge', '1 Exhaust...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of...",K69736336
2810,3 BHK Flat in Sector-2 Sohna,https://www.99acres.com/3-bhk-bedroom-apartmen...,Supertech Hill Town,1.5 Crore,"₹ 8,720/sq.ft.",Carpet area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3+ Balconies,NaN,"L342c, Sector-2 Sohna, Gurgaon, Haryana",3rd of 4 Floors,East,Under Construction,"['Discount Department Store', 'Omaxe Gurgaon M...","Spacious rooms, amazing locality, situated on ...",[],"['Lift(s)', 'Maintenance Staff', 'Swimming Poo...",NaN,A67340870
2582,2 BHK Flat in Sector-33 Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Central Park Flower Valley Cerise Floors,1.3 Crore,"₹ 10,743/sq.ft.",Super Built up area 1210(112.41 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"G-136, Sector-33 Sohna, Gurgaon, Haryana",3rd of 4 Floors,North,Within 6 months,"['Sector 55-56, Sector 56', 'M3m 65th Avenue M...",It has a exclusive terrace area along with it,[],"['Lift(s)', 'Water Storage', 'Park', 'Visitor ...",NaN,U68925974
560,3 BHK Flat in Sector 102 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Emaar Gurgaon Greens4.1 ★,1.3 Crore,"₹ 7,878/sq.ft.",Super Built up area 1650(153.29 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,Servant Room,"A123, Sector 102 Gurgaon, Gurgaon, Haryana",7th of 14 Floors,North-East,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...","A 3 bedroom flat, located in sector-102 gurgao...","['1 Geyser', 'No AC', 'No Bed', 'No Chimney', ...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Construction4 out of...",Q61696670

In [65]:
df.shape

(3017, 20)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3017 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3017 non-null   object
 1   link             3017 non-null   object
 2   society          3016 non-null   object
 3   price            3007 non-null   object
 4   area             3004 non-null   object
 5   areaWithType     3008 non-null   object
 6   bedRoom          3008 non-null   object
 7   bathroom         3008 non-null   object
 8   balcony          3008 non-null   object
 9   additionalRoom   1694 non-null   object
 10  address          3002 non-null   object
 11  floorNum         3006 non-null   object
 12  facing           2127 non-null   object
 13  agePossession    3007 non-null   object
 14  nearbyLocations  2913 non-null   object
 15  description      3008 non-null   object
 16  furnishDetails   2203 non-null   object
 17  features         2594 non-null   object
 18  rating           2676 non-null   object
 19  property_id      3008 non-null   object
dtypes: object(20)
memory usage: 471.5+ KB

In [67]:
df.isnull().sum()

property_name         0
link                  0
society               1
price                10
area                 13
areaWithType          9
bedRoom               9
bathroom              9
balcony               9
additionalRoom     1323
address              15
floorNum             11
facing              890
agePossession        10
nearbyLocations     104
description           9
furnishDetails      814
features            423
rating              341
property_id           9
dtype: int64

In [68]:
df.drop(columns=['link','property_id'],inplace=True)

In [69]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [70]:
df.rename(columns={'area':'price_per_sqft'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [71]:
df['price_per_sqft'].isnull().sum()

np.int64(13)

In [72]:
df=df[~df['price_per_sqft'].isnull()]
df.shape

(3004, 18)

In [73]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [74]:
df['price_per_sqft']=df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

In [75]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [76]:
df['price'].str.split(' ').str.get(1).value_counts()

price
Crore    2074
Lac       922
Name: count, dtype: int64

In [77]:
def convert_price(price):
  if type(price) == float:
    return price;
  else:
    if price[1]=='Lac':
      return round(float(price[0])/100,2);
    else:
      return round(float(price[0]),2)

In [78]:
df['price']=df['price'].str.split(' ').apply(convert_price)

In [79]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [80]:
df['society'].value_counts().shape

(634,)

In [81]:
df['society']=df['society'].str.lower()

In [82]:
df['society'].value_counts()

society
ss the leaf3.8 ★                                     73
tulip violet4.3 ★                                    40
shapoorji pallonji joyville gurugram4.0 ★            39
signature global park4.0 ★                           36
shree vardhman victoria3.8 ★                         35
tulip violet4.2 ★                                    33
smart world orchard                                  32
emaar mgf emerald floors premier3.8 ★                32
smart world gems                                     32
paras dews                                           31
dlf the ultima4.0 ★                                  31
dlf regal gardens3.9 ★                               30
shree vardhman flora3.8 ★                            29
m3m woodshire4.0 ★                                   29
la vida by tata housing                              28
signature global solera3.7 ★                         27
godrej nature plus                                   27
emaar gurgaon greens4.1 ★                            25
bptp terra3.8 ★                                      25
vatika gurgaon 213.7 ★                               24
dlf new town heights 13.9 ★                          24
eldeco accolade3.8 ★                                 24
experion the heartsong3.9 ★                          24
bestech park view residency3.9 ★                     23
tata primanti4.1 ★                                   22
m3m heights                                          22
emaar palm gardens4.1 ★                              22
ats triumph3.9 ★                                     22
sare crescent parc3.5 ★                              21
rof ananda                                           21
godrej 1014.0 ★                                      20
experion windchants3.8 ★                             20
antriksh heights3.7 ★                                19
sare homes                                           19
indiabulls centrum park3.7 ★                         18
sobha city                                           18
ambience creacions                                   18
mapsko mount ville4.1 ★                              18
m3m skywalk                                          18
ats tourmaline3.9 ★                                  18
chd avenue 713.6 ★                                   18
pareena coban residences                             17
supertech araville                                   17
gls arawali homes3.8 ★                               17
m3m golfestate4.4 ★                                  17
conscient heritage max4.3 ★                          17
hcbs sports ville3.6 ★                               16
m3m merlin3.7 ★                                      16
bestech park view grand spa4.3 ★                     16
godrej summit3.7 ★                                   16
ansal heights 86                                     15
godrej oasis3.9 ★                                    15
umang monsoon breeze                                 15
emaar mgf the palm drive4.1 ★                        15
ireo skyon4.0 ★                                      14
umang winter hills3.9 ★                              14
ramsons kshitij3.7 ★                                 14
corona optus3.9 ★                                    14
orchid petals4.1 ★                                   14
the close north4.0 ★                                 14
vatika the seven lamps3.8 ★                          14
imperia the esfera                                   14
mvn athens3.7 ★                                      14
indiabulls enigma                                    14
dlf the primus3.9 ★                                  14
ireo victory valley4.1 ★                             14
puri emerald bay3.7 ★                                13
bestech park view ananda4.2 ★                        13
ireo the corridors                                   13
central park flower valley                           13
tarc maceo3.8 ★                                      11
sbtl caladium                                        11
breez global hill view                               11
alpha corp gurgaonone 844.0 ★                        11
m3m soulitude                                        11
raheja vedaanta3.6 ★                                 11
adani m2k oyster grande3.9 ★                         11
godrej aria3.8 ★                                     11
dlf the skycourt4.2 ★                                11
godrej air                                           10
ramprastha the edge towers3.5 ★                      10
ats kocoon                                           10
pyramid urban homes 2                                10
emaar mgf palm hills4.0 ★                            10
puri diplomatic greens4.0 ★                          10
signature global synera3.4 ★                         10
capital residences 360                               10
dlf new town heights 24.0 ★                          10
zara aavaas                                          10
pivotal devaan                                       10
breez global heights4.2 ★                            10
microtek greenburg3.8 ★                               9
aipl the peaceful homes3.9 ★                          9
ild greens4.1 ★                                       9
vatika city4.1 ★                                      9
parsvnath green ville3.9 ★                            9
bestech park view sanskruti4.2 ★                      9
pareena mi casa                                       9
avl 36 gurgaon3.7 ★                                   8
gls avenue 51                                         8
bestech altura                                        8
birla navya                                           8
ss                                                    8
tulip ivory3.5 ★                                      8
vatika lifestyle homes3.8 ★                           8
orris aster court premier                             8
assotech blith                                        8
m3m skycity                                           8
the lions cghs                                        8
m3m capital                                           8
emaar digihomes                                       8
signature andour heights3.8 ★                         7
mapsko casa bella3.8 ★                                7
signature global orchard avenue3.6 ★                  7
sare green parc phase 3                               7
sare crescent parc royal greens phase 1               7
aipl zen residences                                   7
orris carnation residency3.7 ★                        7
trisara our homes 3                                   7
vipul lavanya3.9 ★                                    7
emaar imperial gardens3.8 ★                           7
signature global city                                 7
ansal housing highland park                           7
ireo the grand arch4.0 ★                              7
shapoorji pallonji joyville gurugram                  6
ashiana mulberry                                      6
supertech hues                                        6
bestech park view spa next4.0 ★                       6
kiran residency                                       6
mapsko royale ville3.7 ★                              6
signature the roselia3.6 ★                            6
signature global city 63a                             6
parsvnath exotica3.7 ★                                6
pyramid urban                                         6
greenopolis                                           6
hero homes                                            6
suncity vatsal valley                                 6
bestech park view city4.1 ★                           6
sidhartha ncr one phase 14.2 ★                        6
hsiidc sidco aravali                                  6
signature global park 4                               6
pioneer araya3.8 ★                                    6
m3m sierra 68                                         6
bptp astaire gardens3.7 ★                             6
dlf regency park 13.6 ★                               6
godrej habitat                                        5
signature global grand iva3.9 ★                       5
ireo uptown4.1 ★                                      5
dlf park place4.1 ★                                   5
signature global the millennia                        5
central park resorts4.4 ★                             5
adani brahma samsara vilasa                           5
dlf regency park 24.0 ★                               5
signature global city 92                              5
m3m the marina4.0 ★                                   5
conscient elevate                                     5
tulip monsella                                        5
signature global city 37d ph 2                        5
ats marigold                                          5
central park flower valley aqua front towers          5
emaar mgf emerald estate3.8 ★                         5
vatika city homes3.9 ★                                5
signature global city 81                              5
vatika sovereign park                                 5
silverglades the melia                                5
apna enclave                                          5
pareena laxmi apartments3.6 ★                         5
krisumi waterfall residences                          5
green court3.7 ★                                      5
satya the hermitage3.5 ★                              5
ashiana anmol3.5 ★                                    5
essel towers                                          5
pioneer park3.8 ★                                     5
lotus homz4.0 ★                                       4
raheja navodaya3.6 ★                                  4
sare petioles                                         4
orris aster court                                     4
dlf new town heights3.7 ★                             4
essel tower                                           4
railway officers rpf society                          4
unitech vistas                                        4
dlf the arbour                                        4
ild grand                                             4
dlf the skycourt                                      4
hsiidc sidco shivalik apartments3.8 ★                 4
global hill view                                      4
godrej frontier3.7 ★                                  4
ramprastha primera                                    4
unitech fresco3.8 ★                                   4
ss the coralwood3.4 ★                                 4
godrej icon                                           4
corona gracieux                                       4
ramprastha skyz                                       4
prime habitat                                         4
emaar palm heights                                    4
signature the serenas                                 4
tata gurgaon gateway3.8 ★                             4
tulip petals3.6 ★                                     3
valley view estate                                    3
sukhshanti apartment                                  3
ss almeria                                            3
ambience lagoon3.9 ★                                  3
sare green parc                                       3
adani aangan arcade                                   3
spaze privy3.9 ★                                      3
conscient habitat3.6 ★                                3
tulip lemon3.9 ★                                      3
dlf belvedere towers3.8 ★                             3
aipl club residences                                  3
krrish florence estate                                3
piedmont taksila heights3.6 ★                         3
pivotal riddhi siddhi                                 3
signature global solera 2                             3
dlf carlton estate4.0 ★                               3
whiteland blissville                                  3
shri ram apartments                                   3
tulip white3.5 ★                                      3
dlf express greens3.9 ★                               3
sare green parc 2                                     3
spaze privvy the address3.9 ★                         3
sapphire eighty three                                 3
dlf the grove                                         3
unitech sunbreeze                                     3
ats kocoon4.2 ★                                       3
spaze privy at43.9 ★                                  3
chintels paradiso3.9 ★                                3
sunischit apartments                                  3
unitech the residences3.7 ★                           3
dlf royalton tower                                    3
sidhartha ncr one                                     3
apex our homes                                        3
puri diplomatic greens3.9 ★                           3
suncity platinum towers                               3
vatika xpressions                                     3
raheja revanta                                        3
dhoot time residency4.0 ★                             3
raheja sampada                                        3
guru gram haryana cghs4.1 ★                           3
paras quartier                                        3
afnhb jalvayu vihar3.7 ★                              3
unitech uniworld gardens3.8 ★                         3
deepak minda                                          3
maxworth city residences                              3
brisk lumbini terrace homes                           3
my home                                               3
siddhartha apartment                                  3
bestech park view city 23.9 ★                         3
raheja atharva3.6 ★                                   3
vatika independent floors3.8 ★                        3
tulip purple                                          3
bhagwati sadan                                        3
satya element one                                     3
unitech heritage city                                 3
kendriya vihar4.1 ★                                   3
sidhartha ncr greens4.3 ★                             3
shree arihant apartment                               3
shri banke bihari society3.8 ★                        3
mahindra aura4.2 ★                                    3
krrish provence estate                                3
pyramid elite                                         3
smriti apartment                                      3
m3m urbana                                            2
palam vihar society                                   2
maruti vihar                                          2
vasant appartments                                    2
park royal apartment                                  2
bptp pedestal                                         2
mrg world ultimus                                     2
mapsko paradise3.9 ★                                  2
landmark the residency                                2
shyam apartment                                       2
suncity heights3.7 ★                                  2
ansal heights3.2 ★                                    2
unitech uniworld gardens 23.4 ★                       2
adani aangan galleria                                 2
housing board colony                                  2
today callidora                                       2
hcbs sports ville                                     2
oriental valley chs                                   2
aqua front towers                                     2
sahara grace                                          2
silverglades hightown residences                      2
jammu and kashmir bank employees cghs3.7 ★            2
shapoorji pallonji joyville                           2
dlf city                                              2
tulip orange3.9 ★                                     2
central park 2 bellevue                               2
mahindra luminare4.0 ★                                2
ramprastha the atrium3.4 ★                            2
vatika inxt floors                                    2
raheja vanya                                          2
puri the aravallis                                    2
the penthouses at the hibiscus                        2
suposhaa smartworld orchard                           2
elan the presidential                                 2
ramprastha city                                       2
ansal api celebrity suites                            2
cghs airport apartment                                2
samaspurkunj                                          2
residency grand                                       2
ss residency                                          2
mittal surya vihar                                    2
ansal api esencia3.7 ★                                2
the close south3.9 ★                                  2
lagoon apartment                                      2
rof aalayas3.8 ★                                      2
awho shanti vihar4.0 ★                                2
m3m sky lofts                                         2
signature global the millennia 3                      2
orchid island4.2 ★                                    2
ganga apartment                                       2
supertech hill town                                   2
suncity avenue 76                                     2
godrej nature plus serenity                           2
ashiana anmol                                         2
ardee city3.8 ★                                       2
nbcc heights3.9 ★                                     2
m3m latitude                                          2
pioneer urban presidia                                2
emaar mgf palm studios                                2
tulip leaf                                            2
tulip violet                                          2
vatika emilia floors3.7 ★                             2
viridian the plaza 106                                2
shree shyam residency                                 2
bestech park view sanskruti4.1 ★                      2
dlf the icon3.7 ★                                     2
green campus chs                                      2
dlf the crest3.6 ★                                    2
bestech spa signature                                 2
m3m ikonic                                            2
lavanya apartments                                    2
professors enclave cghs                               2
om appartments                                        2
bptp freedom park life4.0 ★                           2
emaar mgf the enclave                                 2
vipul belmonte3.9 ★                                   2
vipul world floors                                    2
bptp mansions park prime                              2
element one service                                   2
milan cghs 9                                          2
apartment                                             2
breeze global heights                                 2
paras irene3.7 ★                                      2
dlf the belaire3.9 ★                                  2
suncity avenue 1023.9 ★                               2
bptp amstoria3.8 ★                                    2
surendra avenue 69                                    2
ambience caitriona                                    2
sidhivinayak apartments                               2
tulsiani easy in homes                                2
spire woods now ananda by alpha corp                  1
maa bhagwati residency                                1
parkwood westend                                      1
signature global infinity mall                        1
nul                                                   1
lotus elise                                           1

In [83]:
import re
df['society']=df['society'].apply(lambda name:re.sub(r'\d+(\.\d+)?\s?★','',str(name).strip()))
df['society']

0                              maa bhagwati residency
1                                        apna enclave
2                              tulsiani easy in homes
3                                 smart world orchard
4                                    parkwood westend
5                      signature global infinity mall
6                                          the cocoon
7                                         ats triumph
8                                   vatika xpressions
9                                      raheja revanta
10                           signature global city 81
11                                  hcbs sports ville
12                                 supertech araville
13                                             godrej
14                               shree vardhman flora
15                                         sobha city
16                                       senate court
17               shapoorji pallonji joyville gurugram
19                         central park flower valley
20                                   smart world gems
21                                     bestech altura
22                                   smart world gems
23                             emaar imperial gardens
24                            la vida by tata housing
26                                        the serenas
27                                     m3m golfestate
28           central park resort belgravia residences
29                                      apex builders
30                                     godrej habitat
31                                ompee k s residency
32                                        bhawna cghs
33                                adani aangan arcade
34                                    sare green parc
35                               shree vardhman flora
36                                     supertech hues
37                                  chintels paradiso
38                             breez global hill view
39                                         ild greens
40                               ansal sushant lok ci
41                                   ashiana mulberry
42                                    godrej meridien
43                                  mapsko casa bella
44                                    pooja apartment
45                              signature global park
46                              dlf new town heights
47                                         paras dews
48                                         godrej air
49                                     dlf the primus
50                   emaar mgf emerald floors premier
51                                  dlf regency park
52                                 supertech araville
53                              signature global park
54                           maxworth city residences
55                                       deepak minda
56                              shree shyam residency
57                                     pivotal devaan
58                             unitech the residences
59                                        chd avenue
60                     gokuldham society, bahadurgarh
61                             silverglades the melia
62            sare crescent parc royal greens phase 1
63                                 umang winter hills
64                                    ramprastha skyz
65                                   4s aradhya homes
66                                         ild greens
67                             bptp freedom park life
68                                     godrej habitat
69                                    ramsons kshitij
70                                  sidhartha ncr one
71                                     raheja sampada
72                              signature the serenas
73                           pareena laxmi apartments
74                                satya the hermitage
75                                   smart world gems
76                                  gls arawali homes
77                              signature global park
78                            bestech park view city
79                               shree vardhman flora
80                                afnhb jalvayu vihar
81                                      m3m soulitude
82                                      pyramid elite
83                            emaar mgf palm terraces
84                                    anamika enclave
85                                  hcbs sports ville
86                                 puri the aravallis
87                        brisk lumbini terrace homes
88                            huda ashok vihar phase
89                                            my home
90                              signature global city
91                                        m3m heights
92                              signature global park
93                              signature global park
94                                 godrej nature plus
95                                     supertech hues
96                              dlf new town heights
97       central park flower valley aqua front towers
98                                 ambience creacions
99                          signature global city 63a
100                                      godrej oasis
101                                       m3m skycity
102                                supertech araville
103                               smart world orchard
104                                 hcbs sports ville
105                                emaar palm premier
106                                godrej nature plus
107                                       godrej aria
108                                   ramsons kshitij
109                                     conscient one
110                          pareena laxmi apartments
111                                     pyramid elite
112                                    raheja revanta
113                                       m3m skycity
114                             signature the roselia
115                                    not applicable
116                                godrej nature plus
117                                   ramprastha city
118                                   smartworld 1dxp
119                       ansal housing highland park
120                             czar mahira homes 63a
121                              breez global heights
122                               trisara our homes 3
123                                     m3m soulitude
124                              emaar mgf palm hills
125                                   ramprastha city
126                          pareena coban residences
127                           la vida by tata housing
128                           la vida by tata housing
129                       godrej summit premia towers
130                                        ardee city
131                             m3m one key resiments
132                                  ansal heights 86
133                                        mvn athens
134                             signature the serenas
135                      sushant lok 1 builder floors
136                              umang monsoon breeze
137                                     gls avenue 51
138                           signature global solera
139                                supertech araville
140                                       greenopolis
141      central park flower valley aqua front towers
142                                        sare homes
143         vatika sovereign next sector-82 a gurgaon
144                                    bhagwati sadan
145                                  smart world gems
146                                     micasa sec 68
147                                   eldeco accolade
148                                        hero homes
149                                       shyam sadan
150                                       m3m heights
151                               hanumanta apartment
152                                supertech hilltown
153                                        ashiyara 2
154                                   raheja vedaanta
155                                        bptp terra
156                                       green court
157                            m3m golf hills phase 1
158                     abhinav group housing society
159                             pyramid urban homes 2
160                                       m3m heights
161                                godrej nature plus
162                               smart world orchard
163                                     ashiana anmol
164                              signature signum 95a
165                                umang winter hills
166                                    aardhya homesh
167                                        rof ananda
168                                  smart world gems
169                                    assotech blith
170                                       essel tower
171                                      raheja vanya
172                                vatika inxt floors
173                               palam vihar society
174                                      godrej oasis
175                              dlf new town heights
176                              dlf new town heights
177     sonata group housing society sector 1 manesar
178                                    supertech hues
179                            krrish florence estate
180                          piedmont taksila heights
181                                experion heartsong
182                                       ss the leaf
183                                        m3m urbana
184                               aipl zen residences
185                                 dlf regal gardens
186                                        godrej air
187                             suncity vatsal valley
188                             shree shyam residency
189                            project krishna colony
190                                        mvn athens
191                                 m3m antalya hills
192                        central park flower valley
193                                       m3m capital
194                                     ansal heights
195                                      malibu towne
196                               aipl zen residences
197                                       m3m heights
198                                 hcbs sports ville
199                                 hcbs sports ville
200                                        jmd empire
201                              housing apna enclave
202                                    assotech blith
203                                   pareena mi casa
204                                   suncity heights
205                                        lotus homz
206                    ramson kshitij sec-95 gurugram
207                               maruti vihar colony
208                                       m3m heights
209                                  supertech basera
210                    signature global the millennia
211                                     m3m soulitude
212                                      raheja vanya
213        ganpati apartment  2, laxman vihar phase 1
214                             ramprastha the atrium
215                                    m3m golfestate
216                                   eldeco accolade
217                                       m3m heights
218                                       m3m heights
219                             vatika sovereign next
220                                       m3m heights
221                                       m3m heights
222                                       m3m heights
223                               south city 1 floors
224                                      allure homes
225                                       zara aavaas
226                          sidhartha ncr one phase
227                                       chd avenue
228                        ramprastha the edge towers
229                                supertech araville
230                                 imperia aashiyara
231                           la vida by tata housing
232              shapoorji pallonji joyville gurugram
233                               smart world orchard
234                                supertech araville
235                               smart world orchard
236                            unitech the residences
237                            emaar imperial gardens
238                                        sare homes
239                                       greenopolis
240                                    pivotal devaan
241                                   today callidora
242            m m residency, krishna colony, gurgaon
243                           signature global park 4
244                                       chd avenue
245                              park royal apartment
246           vatika boulevard residences and heights
247                    signature global the millennia
248                                       m3m heights
249              shapoorji pallonji joyville gurugram
250                                    tulip monsella
251                     shyamkunj ashok vihar pahse 2
252                                godrej nature plus
253                                       m3m heights
254                                    m3m the marina
255                                   emaar digihomes
256                              umang monsoon breeze
257                                   mapsko paradise
258                                    cancon enclave
259                                     tata primanti
260                                 mrg world ultimus
261                        sonata group housing gh 24
262                                     bptp pedestal
263                               smart world orchard
264                              hsiidc sidco aravali
265                                       godrej aria
266                                    assotech blith
267                                sare crescent parc
268                                    unitech vistas
269                                supertech araville
270                       ansal housing highland park
271                                       tulip white
272                                 mapsko casa bella
273                         unitech uniworld gardens
274                                         ild grand
275                                       m3m capital
276                                    unitech vistas
277                        ramprastha the edge towers
278                                  smart world gems
279                             sapphire eighty three
280                          pareena coban residences
281                                sare crescent parc
282                                     dlf the grove
283                                 baani city center
284                                 indiabulls enigma
285                                       ss the leaf
286                               smart world one dxp
287                              sukhshanti apartment
288                                    m3m golfestate
289                       bestech park view residency
290                                        ss almeria
291                                       jmd gardens
292                              cghs agrim apartment
293                                  global hill view
294                               ireo victory valley
295                                   emaar digihomes
296                                godrej nature plus
297                                dlf carlton estate
298                               smart world orchard
299                             signature global park
300                      railway officers rpf society
301                                        godrej air
302                              emaar mgf palm hills
303                                      maruti vihar
304                                vasant appartments
305                                  ansal heights 86
306              shapoorji pallonji joyville gurugram
307                                puri the aravallis
308                                   the close north
309                               smart world orchard
310                              emaar gurgaon greens
311                                godrej nature plus
312                            landmark the residency
313                                       m3m capital
314                            emaar imperial gardens
315                              dlf belvedere towers
316                                         m3m crown
317                                           godrej
318                              central park resorts
319                              sukhshanti apartment
320                                    m3m golfestate
321                       bestech park view residency
322                                        ss almeria
323                               ireo victory valley
324                                   emaar digihomes
325                                dlf carlton estate
326                             signature global park
327                      railway officers rpf society
328                                        godrej air
329                              emaar mgf palm hills
330                                      maruti vihar
331                                vasant appartments
332                                  ansal heights 86
333              shapoorji pallonji joyville gurugram
334                                   the close north
335                              emaar gurgaon greens
336                            landmark the residency
337                            emaar imperial gardens
338                              dlf belvedere towers
339                                           godrej
340                                    tulip monsella
341           sare crescent parc royal greens phase 1
342                              aipl club residences
343                            experion the heartsong
344                             signature global city
345                            bestech park view city
346                                emaar palm gardens
347                                       chd avenue
348                                        mvn athens
349                                 mahindra luminare
350                                   raheja navodaya
351                                godrej nature plus
352                                        m3m urbana
353                            experion the heartsong
354                                        sobha city
355                                godrej nature plus
356                               smart world orchard
357                          emaar mgf the palm drive
358                       bestech park view residency
359                       bestech park view residency
360                                        m3m merlin
361                                  dlf the skycourt
362                              emaar gurgaon greens
363                               afnhb jalvayu vihar
364                                 dlf regency park
365                               ireo victory valley
366                                ambience creacions
367                          signature global city 92
368      the khushboo cooperative housing society ltd
369                           adani m2k oyster grande
370                              dlf belvedere towers
371                                        sobha city

In [84]:
df['society'].value_counts().shape

(605,)

In [85]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [86]:
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     943
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [87]:
df[df['bedRoom'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2850,4 BHK Flat in Sector 53 Gurgaon,tulip monsella,NaN,33198.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2851,2 BHK Flat in New Palam Vihar,my home,NaN,4400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2852,2 BHK Flat in Sohna,breez global hill view,NaN,5470.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2922,3 BHK Flat in Sector 99A Gurgaon,pareena coban residences,NaN,5759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2923,1 BHK Flat in Golf Course Ext Road,ikon tower baani city centre,NaN,12437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2924,2 BHK Flat in Sector 89 Gurgaon,greenopolis,NaN,4820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2926,4 BHK Flat in C Block Sushant Lok Phase 1,maple heights,NaN,8888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2927,2 BHK Flat in Sector 99 Gurgaon,assotech blith,NaN,6593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
df=df[~df['bedRoom'].isnull()]

In [89]:
df.shape

(2996, 18)

In [90]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [91]:
df['bedRoom']=df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [92]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [93]:
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1043
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64

In [94]:
df['bathroom'].isnull().sum()

np.int64(0)

In [95]:
df['bathroom']=df['bathroom'].str.split(' ').str.get(0).astype('int')
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [96]:
df['balcony'].value_counts()

balcony
3 Balconies     973
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [97]:
df['balcony'].isnull().sum()

np.int64(0)

In [98]:
df['balcony']=df['balcony'].str.split(' ').str.get(0).str.replace('No','0')
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [99]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Servant Room,Study Room                            8
Study Room,Pooja Room                              8
Study Room,Servant Room,Store Room                 7
Pooja Room,Servant Room,Others                     6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Store Room                              6
Others,Servant Room                                6
Pooja Room,Others                                  6
Study Room,Servant Room,Others                     5
Pooja Room,Study Room,Store Room                   4
Pooja Room,Store Room,Study Room,Servant Room      4
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Pooja Room,Study Room,Store Room      3
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Servant Room,Study Room,Store Room                 2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Pooja Room,Study Room,Others                       2
Store Room,Pooja Room,Servant Room                 1
Pooja Room,Study Room,Store Room,Servant Room      1
Pooja Room,Servant Room,Study Room,Store Room      1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [100]:
df['additionalRoom'].value_counts().shape

(49,)

In [101]:
df['additionalRoom'].isnull().sum()

np.int64(1304)

In [102]:
df['additionalRoom'].fillna('not available',inplace=True)

/tmp/ipython-input-1615843200.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not available',inplace=True)

In [103]:
df['additionalRoom']=df['additionalRoom'].str.lower()

In [104]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [105]:
df['floorNum'].value_counts()

floorNum
2nd   of 4 Floors           74
3rd   of 4 Floors           71
4th   of 4 Floors           62
1st   of 4 Floors           61
12nd   of 14 Floors         49
14th   of 14 Floors         48
Ground of 14 Floors         40
10th   of 14 Floors         35
7th   of 14 Floors          35
8th   of 14 Floors          34
4th   of 14 Floors          28
6th   of 14 Floors          27
2nd   of 2 Floors           26
3rd   of 3 Floors           26
1st   of 14 Floors          26
8th   of 19 Floors          24
5th   of 14 Floors          24
3rd   of 14 Floors          24
9th   of 9 Floors           23
9th   of 14 Floors          23
1st   of 1 Floors           23
5th   of 12 Floors          22
2nd   of 3 Floors           22
11st   of 14 Floors         22
2nd   of 14 Floors          21
8th   of 18 Floors          20
10th   of 19 Floors         18
6th   of 18 Floors          18
Ground of 1 Floors          17
7th   of 15 Floors          17
10th   of 18 Floors         17
7th   of 18 Floors          17
12nd   of 12 Floors         17
9th   of 13 Floors          17
5th   of 15 Floors          16
3rd   of 18 Floors          16
9th   of 15 Floors          15
1st   of 3 Floors           15
6th   of 12 Floors          15
2nd   of 12 Floors          15
6th   of 19 Floors          14
1st   of 2 Floors           13
10th   of 26 Floors         13
3rd   of 13 Floors          13
6th   of 10 Floors          13
5th   of 5 Floors           13
Ground of 4 Floors          13
7th   of 7 Floors           13
10th   of 10 Floors         12
6th   of 15 Floors          12
8th   of 12 Floors          11
16th   of 19 Floors         11
8th   of 8 Floors           11
9th   of 26 Floors          11
15th   of 19 Floors         11
11st   of 18 Floors         11
9th   of 24 Floors          11
6th   of 6 Floors           11
17th   of 17 Floors         11
4th   of 10 Floors          11
4th   of 13 Floors          11
2nd   of 19 Floors          10
6th   of 13 Floors          10
7th   of 26 Floors          10
4th   of 12 Floors          10
3rd   of 5 Floors           10
10th   of 12 Floors         10
1st   of 26 Floors          10
7th   of 21 Floors          10
12nd   of 18 Floors         10
3rd   of 9 Floors           10
7th   of 13 Floors          10
4th   of 15 Floors          10
15th   of 29 Floors          9
14th   of 19 Floors          9
8th   of 22 Floors           9
12nd   of 17 Floors          9
8th   of 15 Floors           9
9th   of 20 Floors           9
13rd   of 14 Floors          9
14th   of 15 Floors          9
3rd   of 12 Floors           9
7th   of 12 Floors           9
5th   of 18 Floors           9
6th   of 26 Floors           9
7th   of 17 Floors           9
18th   of 19 Floors          9
6th   of 16 Floors           9
8th   of 13 Floors           8
8th   of 24 Floors           8
1st   of 19 Floors           8
3rd   of 19 Floors           8
10th   of 13 Floors          8
5th   of 13 Floors           8
10th   of 17 Floors          8
5th   of 9 Floors            8
9th   of 18 Floors           8
12nd   of 24 Floors          8
2nd   of 15 Floors           8
4th   of 26 Floors           8
12nd   of 26 Floors          8
3rd   of 15 Floors           8
2nd   of 5 Floors            8
2nd   of 8 Floors            8
8th   of 26 Floors           8
9th   of 12 Floors           8
14th   of 24 Floors          8
12nd   of 19 Floors          8
11st   of 26 Floors          7
10th   of 21 Floors          7
9th   of 19 Floors           7
12nd   of 15 Floors          7
5th   of 29 Floors           7
8th   of 21 Floors           7
11st   of 11 Floors          7
7th   of 19 Floors           7
5th   of 20 Floors           7
12nd   of 13 Floors          7
8th   of 10 Floors           7
2nd   of 13 Floors           7
4th   of 19 Floors           7
16th   of 16 Floors          7
2nd   of 17 Floors           7
1st   of 13 Floors           7
11st   of 24 Floors          7
13rd   of 13 Floors          7
2nd   of 10 Floors           7
11st   of 13 Floors          7
Ground of 3 Floors           6
11st   of 19 Floors          6
1st   of 5 Floors            6
11st   of 12 Floors          6
14th   of 27 Floors          6
5th   of 25 Floors           6
2nd   of 20 Floors           6
5th   of 22 Floors           6
10th   of 29 Floors          6
12nd   of 22 Floors          6
17th   of 19 Floors          6
Ground of 16 Floors          6
1st   of 10 Floors           6
10th   of 15 Floors          6
4th   of 18 Floors           6
15th   of 15 Floors          6
3rd   of 25 Floors           6
Ground of 15 Floors          6
5th   of 10 Floors           6
4th   of 17 Floors           6
16th   of 18 Floors          6
7th   of 20 Floors           6
10th   of 20 Floors          6
6th   of 9 Floors            6
19th   of 19 Floors          6
9th   of 11 Floors           5
4th   of 27 Floors           5
6th   of 11 Floors           5
9th   of 30 Floors           5
14th   of 16 Floors          5
8th   of 30 Floors           5
Ground of 12 Floors          5
15th   of 21 Floors          5
1st   of 15 Floors           5
10th   of 25 Floors          5
15th   of 18 Floors          5
7th   of 8 Floors            5
8th   of 9 Floors            5
10th   of 27 Floors          5
18th   of 29 Floors          5
4th   of 9 Floors            5
Ground of 19 Floors          5
12nd   of 21 Floors          5
11st   of 25 Floors          5
6th   of 20 Floors           5
16th   of 26 Floors          5
Ground of 21 Floors          5
15th   of 28 Floors          5
1st   of 12 Floors           5
12nd   of 29 Floors          5
11st   of 16 Floors          5
11st   of 29 Floors          5
10th   of 24 Floors          5
7th   of 27 Floors           5
1st   of 7 Floors            5
11st   of 30 Floors          5
14th   of 29 Floors          5
5th   of 19 Floors           5
4th   of 22 Floors           5
6th   of 17 Floors           5
9th   of 22 Floors           5
3rd   of 20 Floors           5
5th   of 8 Floors            5
3rd   of 10 Floors           4
3rd   of 17 Floors           4
14th   of 21 Floors          4
7th   of 11 Floors           4
3rd   of 22 Floors           4
13rd   of 21 Floors          4
13rd   of 19 Floors          4
1st   of 18 Floors           4
11st   of 15 Floors          4
7th   of 10 Floors           4
19th   of 24 Floors          4
Ground of 17 Floors          4
5th   of 23 Floors           4
4th   of 8 Floors            4
12nd   of 16 Floors          4
7th   of 24 Floors           4
13rd   of 25 Floors          4
15th   of 23 Floors          4
18th   of 32 Floors          4
2nd   of 16 Floors           4
11st   of 17 Floors          4
15th   of 32 Floors          4
11st   of 20 Floors          4
19th   of 40 Floors          4
14th   of 18 Floors          4
5th   of 24 Floors           4
Ground of 13 Floors          4
6th   of 30 Floors           4
17th   of 18 Floors          4
14th   of 26 Floors          4
15th   of 25 Floors          4
25th   of 25 Floors          4
23rd   of 26 Floors          4
5th   of 16 Floors           4
22nd   of 30 Floors          4
7th   of 9 Floors            4
22nd   of 24 Floors          4
2nd   of 11 Floors           4
15th   of 26 Floors          4
9th   of 10 Floors           4
12nd   of 30 Floors          4
14th   of 17 Floors          4
3rd   of 11 Floors           4
17th   of 24 Floors          4
17th   of 26 Floors          4
8th   of 20 Floors           4
15th   of 16 Floors          4
8th   of 16 Floors           4
17th   of 25 Floors          4
20th   of 26 Floors          4
20th   of 20 Floors          4
2nd   of 9 Floors            4
30th   of 32 Floors          3
1st   of 35 Floors           3
21st   of 24 Floors          3
31st   of 32 Floors          3
6th   of 21 Floors           3
10th   of 30 Floors          3
8th   of 17 Floors           3
20th   of 28 Floors          3
Ground of 26 Floors          3
7th   of 23 Floors           3
1st   of 25 Floors           3
1st   of 11 Floors           3
3rd   of 26 Floors           3
10th   of 16 Floors          3
3rd   of 8 Floors            3
9th   of 40 Floors           3
18th   of 26 Floors          3
15th   of 22 Floors          3
9th   of 16 Floors           3
6th   of 23 Floors           3
13rd   of 15 Floors          3
26th   of 30 Floors          3
16th   of 20 Floors          3
12nd   of 27 Floors          3
6th   of 22 Floors           3
6th   of 24 Floors           3
21st   of 22 Floors          3
5th   of 30 Floors           3
15th   of 40 Floors          3
5th   of 17 Floors           3
8th   of 11 Floors           3
10th   of 23 Floors          3
15th   of 20 Floors          3
18th   of 30 Floors          3
2nd   of 22 Floors           3
5th   of 26 Floors           3
6th   of 8 Floors            3
Ground of 18 Floors          3
9th   of 21 Floors           3
15th   of 39 Floors          3
24th   of 24 Floors          3
19th   of 29 Floors          3
18th   of 18 Floors          3
4th   of 29 Floors           3
19th   of 21 Floors          3
4th   of 16 Floors           3
4th   of 21 Floors           3
3rd   of 16 Floors           3
6th   of 29 Floors           3
17th   of 20 Floors          3
11st   of 27 Floors          3
14th   of 32 Floors          3
8th   of 25 Floors           3
8th   of 40 Floors           3
27th   of 27 Floors          3
17th   of 29 Floors          3
19th   of 30 Floors          3
12nd   of 23 Floors          3
2nd   of 26 Floors           3
10th   of 28 Floors          3
17th   of 30 Floors          3
4th   of 20 Floors           3
23rd   of 23 Floors          3
15th   of 45 Floors          2
17th   of 33 Floors          2
5th   of 11 Floors           2
40th   of 40 Floors          2
1st   of 16 Floors           2
Ground of 51 Floors          2
Lower Ground of 4 Floors     2
10th   of 22 Floors          2
28th   of 30 Floors          2
16th   of 36 Floors          2
10th   of 32 Floors          2
2nd   of 21 Floors           2
7th   of 16 Floors           2
3rd   of 29 Floors           2
10th   of 11 Floors          2
4th   of 5 Floors            2
1st   of 24 Floors           2
2nd   of 32 Floors           2
9th   of 17 Floors           2
21st   of 27 Floors          2
7th   of 22 Floors           2
2nd   of 40 Floors           2
7th   of 29 Floors           2
4th   of 34 Floors           2
9th   of 28 Floors           2
9th   of 27 Floors           2
25th   of 30 Floors          2
16th   of 21 Floors          2
16th   of 27 Floors          2
16th   of 32 Floors          2
3rd   of 32 Floors           2
8th   of 29 Floors           2
20th   of 23 Floors          2
1st   of 22 Floors           2
14th   of 20 Floors          2
8th   of 32 Floors           2
15th   of 17 Floors          2
20th   of 25 Floors          2
13rd   of 40 Floors          2
8th   of 34 Floors           2
39th   of 40 Floors          2
3rd   of 27 Floors           2
8th   of 28 Floors           2
7th   of 36 Floors           2
6th   of 31 Floors           2
12nd   of 25 Floors          2
1st   of 20 Floors           2
18th   of 24 Floors          2
14th   of 28 Floors          2
18th   of 21 Floors          2
11st   of 21 Floors          2
20th   of 22 Floors          2
11st   of 23 Floors          2
25th   of 29 Floors          2
19th   of 27 Floors          2
8th   of 23 Floors           2
10th   of 40 Floors          2
13rd   of 30 Floors          2
13rd   of 20 Floors          2
15th   of 24 Floors          2
16th   of 24 Floors          2
4th   of 11 Floors           2
23rd   of 29 Floors          2
16th   of 30 Floors          2
Ground of 23 Floors          2
19th   of 20 Floors          2
17th   of 23 Floors          2
9th   of 29 Floors           2
2nd   of 7 Floors            2
2nd   of 18 Floors           2
3rd   of 24 Floors           2
16th   of 34 Floors          2
4th   of 7 Floors            2
2nd   of 25 Floors           2
2nd   of 24 Floors           2
7th   of 30 Floors           2
2nd   of 6 Floors            2
2nd   of 28 Floors           2
27th   of 29 Floors          2
15th   of 31 Floors          2
43   of 47 Floors            2
24th   of 30 Floors          2
3rd   of 33 Floors           2
1st   of 17 Floors           2
23rd   of 34 Floors          2
1st   of 8 Floors            2
22nd   of 25 Floors          2
1st   of 30 Floors           2
20th   of 47 Floors          1
27th   of 48 Floors          1
33rd   of 48 Floors          1
6th   of 7 Floors            1
26th   of 47 Floors          1
35th   of 35 Floors          1
38th   of 40 Floors          1
12nd   of 39 Floors          1
2nd   of 27 Floors           1
19th   of 39 Floors          1
19th   of 22 Floors          1
19th   of 26 Floors          1
5th   of 6 Floors            1
8th   of 35 Floors           1
34th   of 42 Floors          1
24th   of 27 Floors          1
13rd   of 47 Floors          1
5th   of 35 Floors           1
4th   of 40 Floors           1
32nd   of 32 Floors          1
14th   of 51 Floors          1
21st   of 41 Floors          1
17th   of 31 Floors          1
27th   of 30 Floors          1
34th   of 34 Floors          1
21st   of 23 Floors          1
31st   of 40 Floors          1
18th   of 20 Floors          1
11st   of 22 Floors          1
15th   of 27 Floors          1
24th   of 31 Floors          1
7th   of 42 Floors           1
24th   of 32 Floors          1
8th   of 27 Floors           1
28th   of 29 Floors          1
1st   of 44 Floors           1
10th   of 51 Floors          1
2nd   of 34 Floors           1
28th   of 28 Floors          1
Basement of 4 Floors         1
3rd   of 6 Floors            1
15th   of 30 Floors          1
17th   of 21 Floors          1
4th   of 39 Floors           1
8th   of 42 Floors           1
7th   of 25 Floors           1
Ground of 24 Floors          1
18th   of 51 Floors          1
9th   of 42 Floors           1
18th   of 40 Floors          1
8th   of 31 Floors           1
20th   of 30 Floors          1
21st   of 29 Floors          1
26th   of 34 Floors          1
35th   of 51 Floors          1
20th   of 40 Floors          1
22nd   of 28 Floors          1
5th   of 36 Floors           1
18th   of 35 Floors          1
3rd   of 31 Floors           1
24th   of 36 Floors          1
17th   of 22 Floors          1
18th   of 22 Floors          1
Basement of 13 Floors        1
Ground of 6 Floors           1
Ground of 5 Floors           1
Lower Ground of 1 Floors     1
3rd   of 36 Floors           1
10th   of 33 Floors          1
Ground of 2 Floors           1
21st   of 28 Floors          1
20th   of 32 Floors          1
14th   of 22 Floors          1
33rd   of 42 Floors          1
12nd   of 28 Floors          1
25th   of 36 Floors          1
19th   of 23 Floors          1
4th   of 25 Floors           1
30th   of 40 Floors          1
7th   of 32 Floors           1
4th   of 28 Floors           1
16th   of 25 Floors          1
6th   of 25 Floors           1
19th   of 41 Floors          1
Basement of 28 Floors        1
Ground of 11 Floors          1
3rd   of 40 Floors           1
23rd   of 28 Floors          1
11st   of 36 Floors          1
18th   of 25 Floors          1
16th   of 22 Floors          1
20th   of 34 Floors          1
7th   of 34 Floors           1
13rd   of 18 Floors          1
1st   of 9 Floors            1
20th   of 29 Floors          1
16th   of 51 Floors          1
29th   of 31 Floors          1
5th   of 32 Floors           1
19th   of 31 Floors          1
2nd   of 36 Floors           1
21st   of 51 Floors          1
20th   of 43 Floors          1
24th   of 39 Floors          1
18th   of 23 Floors          1
10th   of 34 Floors          1
12nd   of 32 Floors          1
23rd   of 40 Floors          1
5th   of 27 Floors           1
16th   of 41 Floors          1
3rd   of 28 Floors           1
7th   of 40 Floors           1
17th   of 28 Floors          1
22nd   of 40 Floors          1
19th   of 32 Floors          1
12nd   of 40 Floors          1
16th   of 45 Floors          1
22nd   of 23 Floors          1
21st   of 36 Floors          1
7th   of 28 Floors           1
14th   of 41 Floors          1
3rd   of 30 Floors           1
21st   of 26 Floors          1
10th   of 39 Floors          1
32nd   of 55 Floors          1
22nd   of 26 Floors          1
Ground of 29 Floors          1
Ground of 40 Floors          1
16th   of 35 Floors          1
44   of 47 Floors            1
23rd   of 24 Floors          1
13rd   of 22 Floors          1
17th   of 47 Floors          1
4th   of 6 Floors            1
30th   of 34 Floors          1
24th   of 51 Floors          1
29th   of 29 Floors          1
16th   of 31 Floors          1
5th   of 21 Floors           1
12nd   of 34 Floors          1
5th   of 34 Floors           1
9th   of 25 Floors           1
45   of 47 Floors            1
Ground of 25 Floors          1
9th   of 23 Floors           1
33rd   of 33 Floors          1
1st   of 6 Floors            1
20th   of 24 Floors          1
13rd   of 17 Floors          1
29th   of 39 Floors          1
13rd   of 26 Floors          1
14th   of 25 Floors          1
3rd   of 7 Floors            1
Ground of 22 Floors          1
13rd   of 34 Floors          1
23rd   of 36 Floors          1
Name: count, dtype: int64

In [106]:
df['floorNum'].isnull().sum()

np.int64(2)

In [107]:
df[df['floorNum'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
181,3 BHK Flat in Dwarka Expressway Gurgaon,experion heartsong,1.08,6150.0,Built Up area: 1758 (163.32 sq.m.),3,3,0,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
2766,2 BHK Flat in Sector 78 Gurgaon,nan,0.60,3692.0,Built Up area: 1625 (150.97 sq.m.),2,2,0,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [108]:
df['floorNum']=df['floorNum'].str.split(' ').str.get(0).str.replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [109]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [110]:
df['facing'].value_counts()

facing
North-East    505
East          489
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [111]:
df['facing'].isnull().sum()

np.int64(874)

In [112]:
df['facing'].fillna('NA',inplace=True)

/tmp/ipython-input-3692945726.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA',inplace=True)

In [113]:
df['facing'].value_counts()

facing
NA            874
North-East    505
East          489
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [114]:
df.insert(loc=4,column='area',value=round(df['price']*10000000/df['price_per_sqft']))

In [115]:
df.insert(loc=1,column='property_type',value='flat')

In [116]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2996 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2996 non-null   object
 1   property_type    2996 non-null   object
 2   society          2996 non-null   object
 3   price            2996 non-null   float64
 4   price_per_sqft   2996 non-null   float64
 5   area             2996 non-null   float64
 6   areaWithType     2996 non-null   object
 7   bedRoom          2996 non-null   int64
 8   bathroom         2996 non-null   int64
 9   balcony          2996 non-null   object
 10  additionalRoom   2996 non-null   object
 11  address          2990 non-null   object
 12  floorNum         2994 non-null   object
 13  facing           2996 non-null   object
 14  agePossession    2995 non-null   object
 15  nearbyLocations  2905 non-null   object
 16  description      2996 non-null   object
 17  furnishDetails   2200 non-null   object
 18  features         2589 non-null   object
 19  rating           2668 non-null   object
dtypes: float64(3), int64(2), object(15)
memory usage: 491.5+ KB

In [118]:
df.shape

(2996, 20)

In [119]:
df.to_csv('flats_cleaned.csv',index=False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')